// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import LIB.FSTexFieldMD;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

 
public class Cliente extends javax.swing.JFrame {

 
    public Cliente() {
        initComponents();
        Cliente.this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Cliente = new javax.swing.JDialog();
        lb_cliente = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_nombres = new javax.swing.JLabel();
        lb_apellido = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        but_actualizar = new javax.swing.JButton();
        but_cancelar = new javax.swing.JButton();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jPanelRound1 = new LIB.JPanelRound();
        jEImagePanel1 = new LIB.JEImagePanel();
        jEImagePanel2 = new LIB.JEImagePanel();
        but_atras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rep_proveedor = new javax.swing.JTable();
        but_consultar = new javax.swing.JButton();
        but_eliminar = new javax.swing.JButton();
        but_modificar = new javax.swing.JButton();
        but_limpiar = new javax.swing.JButton();
        txt_consulta = new LIB.FSTexFieldMD();

        lb_cliente.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_cliente.setForeground(new java.awt.Color(102, 0, 0));
        lb_cliente.setText("DATOS DEL CLIENTE");

        lb_id.setText("Id:");

        lb_nombres.setText("Nombres:");

        lb_apellido.setText("Apellidos:");

        lb_direccion.setText("Dirección:");

        lb_telefono.setText("Teléfono:");

        lb_fecha.setText("F. Nacimiento:");

        lb_correo.setText("Correo:");

        but_actualizar.setText("Actualizar");

        but_cancelar.setText("Cancelar");

        javax.swing.GroupLayout Dlg_ClienteLayout = new javax.swing.GroupLayout(Dlg_Cliente.getContentPane());
        Dlg_Cliente.getContentPane().setLayout(Dlg_ClienteLayout);
        Dlg_ClienteLayout.setHorizontalGroup(
            Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lb_cliente))
                    .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                                .addComponent(lb_fecha)
                                .addGap(18, 18, 18)
                                .addComponent(dtcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                                    .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_telefono)
                                        .addComponent(lb_apellido))
                                    .addGap(41, 41, 41)
                                    .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(txt_telefono)))
                                .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                                    .addComponent(lb_direccion)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt_direccion))
                                .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                                    .addComponent(lb_correo)
                                    .addGap(50, 50, 50)
                                    .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                                    .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_nombres)
                                        .addComponent(lb_id))
                                    .addGap(41, 41, 41)
                                    .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nombres)
                                        .addComponent(txt_id)))))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(but_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_cancelar)
                .addGap(123, 123, 123))
        );
        Dlg_ClienteLayout.setVerticalGroup(
            Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dlg_ClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lb_cliente)
                .addGap(27, 27, 27)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombres)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_apellido)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_correo))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_fecha)
                    .addComponent(dtcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(Dlg_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_actualizar)
                    .addComponent(but_cancelar))
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 435));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(null);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CLIENTES.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanelRound1.add(jEImagePanel1);
        jEImagePanel1.setBounds(0, 0, 450, 580);

        jEImagePanel2.setToolTipText("");
        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/recepcion.png"))); // NOI18N

        but_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_atras.setBorder(null);
        but_atras.setBorderPainted(false);
        but_atras.setContentAreaFilled(false);
        but_atras.setFocusPainted(false);

        tbl_rep_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_rep_proveedor);

        but_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/BUSCAR ICO.png"))); // NOI18N
        but_consultar.setBorder(null);
        but_consultar.setBorderPainted(false);
        but_consultar.setContentAreaFilled(false);
        but_consultar.setFocusPainted(false);

        but_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ELIMINAR ICO.png"))); // NOI18N
        but_eliminar.setBorder(null);
        but_eliminar.setBorderPainted(false);
        but_eliminar.setContentAreaFilled(false);
        but_eliminar.setFocusPainted(false);

        but_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/MODIFICAR ICO.png"))); // NOI18N
        but_modificar.setBorderPainted(false);
        but_modificar.setContentAreaFilled(false);
        but_modificar.setFocusPainted(false);

        but_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/LIMPIAR ICO.png"))); // NOI18N
        but_limpiar.setBorder(null);
        but_limpiar.setBorderPainted(false);
        but_limpiar.setContentAreaFilled(false);
        but_limpiar.setFocusPainted(false);

        txt_consulta.setForeground(new java.awt.Color(0, 0, 0));
        txt_consulta.setBordeColorFocus(new java.awt.Color(0, 102, 51));
        txt_consulta.setColorTransparente(true);
        txt_consulta.setPlaceholder("Buscar...");

        javax.swing.GroupLayout jEImagePanel2Layout = new javax.swing.GroupLayout(jEImagePanel2);
        jEImagePanel2.setLayout(jEImagePanel2Layout);
        jEImagePanel2Layout.setHorizontalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel2Layout.createSequentialGroup()
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_atras))
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jEImagePanel2Layout.createSequentialGroup()
                                .addComponent(but_consultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(but_eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(but_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(but_limpiar)))))
                .addContainerGap())
        );
        jEImagePanel2Layout.setVerticalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEImagePanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_eliminar)
                    .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(but_limpiar)
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(but_modificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(but_atras)
                .addContainerGap())
        );

        jPanelRound1.add(jEImagePanel2);
        jEImagePanel2.setBounds(450, 0, 1010, 580);

        getContentPane().add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JDialog getDlg_Cliente() {
        return Dlg_Cliente;
    }
    public void setDlg_Cliente(JDialog Dlg_Cliente) {
        this.Dlg_Cliente = Dlg_Cliente;
    }
    public JButton getBut_atras() {
        return but_atras;
    }
    public void setBut_atras(JButton but_atras) {
        this.but_atras = but_atras;
    }
    public JButton getBut_consultar() {
        return but_consultar;
    }
    public void setBut_consultar(JButton but_consultar) {
        this.but_consultar = but_consultar;
    }
    public JButton getBut_eliminar() {
        return but_eliminar;
    }
    public void setBut_eliminar(JButton but_eliminar) {
        this.but_eliminar = but_eliminar;
    }
    public JButton getBut_limpiar() {
        return but_limpiar;
    }
    public void setBut_limpiar(JButton but_limpiar) {
        this.but_limpiar = but_limpiar;
    }
    public JButton getBut_modificar() {
        return but_modificar;
    }
    public void setBut_modificar(JButton but_modificar) {
        this.but_modificar = but_modificar;
    }
    public JDateChooser getDtcFechaNacimiento() {
        return dtcFechaNacimiento;
    }
    public void setDtcFechaNacimiento(JDateChooser dtcFechaNacimiento) {
        this.dtcFechaNacimiento = dtcFechaNacimiento;
    }
    public JButton getBut_actualizar() {
        return but_actualizar;
    }
    public void setBut_actualizar(JButton but_actualizar) {
        this.but_actualizar = but_actualizar;
    }
    public JButton getBut_cancelar() {
        return but_cancelar;
    }
    public void setBut_cancelar(JButton but_cancelar) {
        this.but_cancelar = but_cancelar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    public JLabel getLb_apellido() {
        return lb_apellido;
    }
    public void setLb_apellido(JLabel lb_apellido) {
        this.lb_apellido = lb_apellido;
    }
    public JLabel getLb_cliente() {
        return lb_cliente;
    }
    public void setLb_cliente(JLabel lb_cliente) {
        this.lb_cliente = lb_cliente;
    }
    public JLabel getLb_correo() {
        return lb_correo;
    }
    public void setLb_correo(JLabel lb_correo) {
        this.lb_correo = lb_correo;
    }
    public JLabel getLb_direccion() {
        return lb_direccion;
    }
    public void setLb_direccion(JLabel lb_direccion) {
        this.lb_direccion = lb_direccion;
    }
    public JLabel getLb_fecha() {
        return lb_fecha;
    }
    public void setLb_fecha(JLabel lb_fecha) {
        this.lb_fecha = lb_fecha;
    }
    public JLabel getLb_id() {
        return lb_id;
    }
    public void setLb_id(JLabel lb_id) {
        this.lb_id = lb_id;
    }
    public JLabel getLb_nombres() {
        return lb_nombres;
    }
    public void setLb_nombres(JLabel lb_nombres) {
        this.lb_nombres = lb_nombres;
    }
    public JLabel getLb_telefono() {
        return lb_telefono;
    }
    public void setLb_telefono(JLabel lb_telefono) {
        this.lb_telefono = lb_telefono;
    }
   
    public JTable getTbl_rep_proveedor() {
        return tbl_rep_proveedor;
    }

    public void setTbl_rep_proveedor(JTable tbl_rep_proveedor) {
        this.tbl_rep_proveedor = tbl_rep_proveedor;
    }

    public JTextField getTxt_apellidos() {
        return txt_apellidos;
    }

    public void setTxt_apellidos(JTextField txt_apellidos) {
        this.txt_apellidos = txt_apellidos;
    }

    public FSTexFieldMD getTxt_consulta() {
        return txt_consulta;
    }

    public void setTxt_consulta(FSTexFieldMD txt_consulta) {
        this.txt_consulta = txt_consulta;
    }



    public JTextField getTxt_correo() {
        return txt_correo;
    }

    public void setTxt_correo(JTextField txt_correo) {
        this.txt_correo = txt_correo;
    }

    public JTextField getTxt_direccion() {
        return txt_direccion;
    }

    public void setTxt_direccion(JTextField txt_direccion) {
        this.txt_direccion = txt_direccion;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nombres() {
        return txt_nombres;
    }

    public void setTxt_nombres(JTextField txt_nombres) {
        this.txt_nombres = txt_nombres;
    }

    public JTextField getTxt_telefono() {
        return txt_telefono;
    }

    public void setTxt_telefono(JTextField txt_telefono) {
        this.txt_telefono = txt_telefono;
    }

    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dlg_Cliente;
    private javax.swing.JButton but_actualizar;
    private javax.swing.JButton but_atras;
    private javax.swing.JButton but_cancelar;
    private javax.swing.JButton but_consultar;
    private javax.swing.JButton but_eliminar;
    private javax.swing.JButton but_limpiar;
    private javax.swing.JButton but_modificar;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JTable tbl_rep_proveedor;
    private javax.swing.JTextField txt_apellidos;
    private LIB.FSTexFieldMD txt_consulta;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//