// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import javax.swing.JButton;
import javax.swing.JLabel;

public class Ingreso extends javax.swing.JFrame {

 
    public Ingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_admin = new javax.swing.JLabel();
        lb_reporte = new javax.swing.JLabel();
        but_Rep_Proveedor = new javax.swing.JButton();
        but_Rep_Producto = new javax.swing.JButton();
        but_Rep_Factura = new javax.swing.JButton();
        but_Rep_Cliente = new javax.swing.JButton();
        but_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 385));
        setPreferredSize(new java.awt.Dimension(500, 385));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_admin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_admin.setText("ADMINISTRADOR");
        getContentPane().add(lb_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 35, -1, -1));

        lb_reporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_reporte.setForeground(new java.awt.Color(0, 0, 204));
        lb_reporte.setText("REPORTES");
        getContentPane().add(lb_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 101, -1, -1));

        but_Rep_Proveedor.setText("REPORTES DE PROVEEDORES");
        but_Rep_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_Rep_ProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(but_Rep_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 136, -1, -1));

        but_Rep_Producto.setText("REPORTES DE PRODUCTOS");
        but_Rep_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_Rep_ProductoActionPerformed(evt);
            }
        });
        getContentPane().add(but_Rep_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 177, 180, -1));

        but_Rep_Factura.setText("REPORTES DE FACTURAS");
        but_Rep_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_Rep_FacturaActionPerformed(evt);
            }
        });
        getContentPane().add(but_Rep_Factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 218, 180, -1));

        but_Rep_Cliente.setText("REPORTES DE CLIENTES");
        but_Rep_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_Rep_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(but_Rep_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 259, 180, -1));

        but_Salir.setText("Salir");
        getContentPane().add(but_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_Rep_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_Rep_ProveedorActionPerformed

    }//GEN-LAST:event_but_Rep_ProveedorActionPerformed

    private void but_Rep_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_Rep_ProductoActionPerformed
        Producto produc = new Producto();
        produc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_Rep_ProductoActionPerformed

    private void but_Rep_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_Rep_FacturaActionPerformed
        Factura fact= new Factura();
        fact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_Rep_FacturaActionPerformed

    private void but_Rep_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_Rep_ClienteActionPerformed
        Cliente clie= new Cliente();
        clie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_but_Rep_ClienteActionPerformed

    public JButton getBut_Rep_Cliente() {
        return but_Rep_Cliente;
    }

    public void setBut_Rep_Cliente(JButton but_Rep_Cliente) {
        this.but_Rep_Cliente = but_Rep_Cliente;
    }

    public JButton getBut_Rep_Factura() {
        return but_Rep_Factura;
    }

    public void setBut_Rep_Factura(JButton but_Rep_Factura) {
        this.but_Rep_Factura = but_Rep_Factura;
    }

    public JButton getBut_Rep_Producto() {
        return but_Rep_Producto;
    }

    public void setBut_Rep_Producto(JButton but_Rep_Producto) {
        this.but_Rep_Producto = but_Rep_Producto;
    }

    public JButton getBut_Rep_Proveedor() {
        return but_Rep_Proveedor;
    }

    public void setBut_Rep_Proveedor(JButton but_Rep_Proveedor) {
        this.but_Rep_Proveedor = but_Rep_Proveedor;
    }

    public JButton getBut_Salir() {
        return but_Salir;
    }

    public void setBut_Salir(JButton but_Salir) {
        this.but_Salir = but_Salir;
    }

    public JLabel getLb_admin() {
        return lb_admin;
    }

    public void setLb_admin(JLabel lb_admin) {
        this.lb_admin = lb_admin;
    }

    public JLabel getLb_reporte() {
        return lb_reporte;
    }

    public void setLb_reporte(JLabel lb_reporte) {
        this.lb_reporte = lb_reporte;
    }


    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_Rep_Cliente;
    private javax.swing.JButton but_Rep_Factura;
    private javax.swing.JButton but_Rep_Producto;
    private javax.swing.JButton but_Rep_Proveedor;
    private javax.swing.JButton but_Salir;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_reporte;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//