// ESPINOZA ALFONSO DAVID, DANNY GUTAMA, JUAN MATUTE, ESTEFANIA MU�OZ//
package VISTA;

import CONECCIÓN_SQL.Dbclientes;
import CONECCIÓN_SQL.SQConnect;
import MODELO.clientes;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

 
public class INGRESAR_CLIENTE extends javax.swing.JFrame {
    
    String name,code,lastname,direc,phone,id,corre;
    
    SQConnect pg= new SQConnect();
    Dbclientes dbu = new Dbclientes();
    ///////////////////////////////////////
    LocalDate hola = LocalDate.now();
    LocalDate chao = LocalDate.now();
    Date dia = new Date();
    Period periodo;
    DefaultTableModel modelo;
    ////////////////////////////////////////////////////////////////////////////

  
    public INGRESAR_CLIENTE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        fechanacimiento = new com.toedter.calendar.JDateChooser();
        ingresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        mostrarbase = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telefonos = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESAR CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setText("CEDULA::");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 20));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 200, -1));

        jLabel3.setText("APELLIDO::");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, -1));

        jLabel4.setText("NOMBRE::");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 20));
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, -1));
        getContentPane().add(fechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 200, -1));

        ingresar.setText("INGRESAR");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jButton2.setText("CANCELAR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel5.setText("FECHA NACIMIENTO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setText("DIRECCIÓN::");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, 20));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, -1));

        jLabel8.setText("CORREO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 180, -1));

        mostrarbase.setText("MOSTRAR BASE");
        mostrarbase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarbaseActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel9.setText("GENERE CODIGO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 20));

        jLabel7.setText("TELEFONO::");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 20));
        getContentPane().add(telefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, -1));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 190, -1));

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CEDULA", "APELLIDO", "NOMBRE", "TELEFONO", "DIRECCION", "FECHA NACIMIENTO", "CODIGO", "CORREO"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 680, -1));

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
       
        
        name=nombre.getText();
        code=codigo.getText();
        lastname=apellido.getText();
        direc=direccion.getText();
        phone=telefonos.getText();
        id=cedula.getText();
        corre=correo.getText();
        dia=fechanacimiento.getDate();
        clientes messi = new clientes();
        
        dbu.setCodigo(code);
        dbu.setCorreo(corre);
        dbu.setCedula(id);
        dbu.setApellido(lastname);
        dbu.setNombre(name);
        dbu.setTelefono(phone);
        dbu.setDireccion(name);
        dbu.setFechanacimiento(dia);
        /////////////////////////////////////////
        if(dbu.insertar()){
        JOptionPane.showMessageDialog(null,"Datos Guardados.");
        
        }else{
        JOptionPane.showMessageDialog(null,"Error al Guardar.");
        } 
         
         
    }//GEN-LAST:event_ingresarActionPerformed

    private void mostrarbaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarbaseActionPerformed
    modelo=(DefaultTableModel)tabla.getModel();
    modelo.setRowCount(0);
    
    List<clientes> per = dbu.mostrarDatos();  
    for (int i = 0; i < per.size(); i++) {
    hola=convertToLocalDateViaMilisecond(per.get(i).getFechanacimiento());
    dia=per.get(i).getFechanacimiento();  ///CARGAR LA FECHA DEL SQL A UN DATE.
    periodo=Period.between(hola,chao); //CALCULAR EL TIEMPO ENTRE FECHAS
    Object [] fila ={per.get(i).getCedula(),per.get(i).getApellido(),per.get(i).getNombre(),per.get(i).getTelefono(),per.get(i).getDireccion(),periodo.getYears(),per.get(i).getCodigo(),per.get(i).getCorreo()};
    modelo.addRow(fila); //AGREGAR LAS FILAS A LA TABLA DE LA INTERFAZ.      
    }
    }//GEN-LAST:event_mostrarbaseActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if(dbu.eliminar(codigo.getText())){
        JOptionPane.showMessageDialog(null,"Datos Eliminados");    
        }else{
        JOptionPane.showMessageDialog(null,"Datos No Eliminados");    
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        dbu.setCorreo(correo.getText());
        dbu.setApellido(apellido.getText());
        dbu.setNombre(nombre.getText());
        dbu.setTelefono(telefonos.getText());
        dbu.setDireccion(direccion.getText());
        dbu.setFechanacimiento(fechanacimiento.getDate());        
        
        if(dbu.modificar(codigo.getText())){
            JOptionPane.showMessageDialog(null,"HECHO");
        }else{
            JOptionPane.showMessageDialog(null,"NO HECHO");
        }
    ////////////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_modificarActionPerformed

    ////////////////////////////////////////////////////////////////////////////
    public LocalDate convertToLocalDateViaMilisecond(Date dateToConvert) {
    return Instant.ofEpochMilli(dateToConvert.getTime())
      .atZone(ZoneId.systemDefault())
      .toLocalDate();
    }
    ////////////////////////////////////////////////////////////////////////////
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INGRESAR_CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INGRESAR_CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INGRESAR_CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INGRESAR_CLIENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INGRESAR_CLIENTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private com.toedter.calendar.JDateChooser fechanacimiento;
    private javax.swing.JButton ingresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton mostrarbase;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefonos;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, DANNY GUTAMA, JUAN MATUTE, ESTEFANIA MU�OZ//