// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;


public class MenuCliente extends javax.swing.JFrame {

    public MenuCliente() {
        initComponents();
        MenuCliente.this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Productos = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SALIR = new javax.swing.JButton();
        CARRITO = new javax.swing.JDialog();
        CANCELAR = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacarrito = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        dejarlo = new javax.swing.JButton();
        contador = new javax.swing.JSpinner();
        jPanelRound1 = new LIB.JPanelRound();
        jEImagePanel1 = new LIB.JEImagePanel();
        jEImagePanel2 = new LIB.JEImagePanel();
        but_granos = new javax.swing.JButton();
        but_verduras = new javax.swing.JButton();
        but_frutas = new javax.swing.JButton();
        but_hierbas = new javax.swing.JButton();
        but_carrito = new javax.swing.JButton();
        but_salir = new javax.swing.JButton();
        but_lacteos = new javax.swing.JButton();
        but_otros = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("COLIBRÍ");

        jLabel2.setText("Código:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));

        jButton1.setText("Añadir al Carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("PROVEEDOR");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Teléfono:");

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("p");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "PROVEEDOR", "DESCRIPCION", "PRECIO", "EXISTENCIA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        SALIR.setText("SALIR");

        javax.swing.GroupLayout Dlg_ProductosLayout = new javax.swing.GroupLayout(Dlg_Productos.getContentPane());
        Dlg_Productos.getContentPane().setLayout(Dlg_ProductosLayout);
        Dlg_ProductosLayout.setHorizontalGroup(
            Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dlg_ProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SALIR)
                .addGap(20, 20, 20))
            .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton1))
                    .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(59, 59, 59)
                        .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Dlg_ProductosLayout.setVerticalGroup(
            Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Dlg_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(Dlg_ProductosLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SALIR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CANCELAR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        comprar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        comprar.setText("EFECTUAR  COMPRA");

        tablacarrito.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablacarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane2.setViewportView(tablacarrito);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo.setText("CARRITO");

        dejarlo.setText("DEJAR PRODUCTO");

        contador.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));

        javax.swing.GroupLayout CARRITOLayout = new javax.swing.GroupLayout(CARRITO.getContentPane());
        CARRITO.getContentPane().setLayout(CARRITOLayout);
        CARRITOLayout.setHorizontalGroup(
            CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CARRITOLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CARRITOLayout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addGroup(CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CARRITOLayout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(titulo)
                            .addGap(113, 113, 113)
                            .addComponent(dejarlo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CARRITOLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(comprar)))
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        CARRITOLayout.setVerticalGroup(
            CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CARRITOLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CARRITOLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titulo)
                        .addGroup(CARRITOLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(dejarlo)))
                    .addGap(27, 27, 27)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(CARRITOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CANCELAR)
                        .addComponent(comprar))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1340, 738));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(null);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PRODUCTOS.png"))); // NOI18N
        jEImagePanel1.setLayout(null);
        jPanelRound1.add(jEImagePanel1);
        jEImagePanel1.setBounds(0, 0, 482, 690);

        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/1.jpg"))); // NOI18N

        but_granos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/GRANOS ICO.png"))); // NOI18N
        but_granos.setBorder(null);
        but_granos.setBorderPainted(false);
        but_granos.setContentAreaFilled(false);
        but_granos.setFocusPainted(false);

        but_verduras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/VERDURAS ICO.png"))); // NOI18N
        but_verduras.setBorder(null);
        but_verduras.setBorderPainted(false);
        but_verduras.setContentAreaFilled(false);
        but_verduras.setFocusPainted(false);
        but_verduras.setMaximumSize(new java.awt.Dimension(3149, 2009));
        but_verduras.setMinimumSize(new java.awt.Dimension(3149, 2009));
        but_verduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_verdurasActionPerformed(evt);
            }
        });

        but_frutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/FRUTAS ICO.png"))); // NOI18N
        but_frutas.setBorder(null);
        but_frutas.setBorderPainted(false);
        but_frutas.setContentAreaFilled(false);
        but_frutas.setFocusPainted(false);

        but_hierbas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/HIERBAS ICO.png"))); // NOI18N
        but_hierbas.setBorder(null);
        but_hierbas.setBorderPainted(false);
        but_hierbas.setContentAreaFilled(false);
        but_hierbas.setFocusPainted(false);

        but_carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/CARRITO ICO.png"))); // NOI18N
        but_carrito.setBorder(null);
        but_carrito.setBorderPainted(false);
        but_carrito.setContentAreaFilled(false);
        but_carrito.setFocusPainted(false);

        but_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/SALIR VERDE-PhotoRoom.png"))); // NOI18N
        but_salir.setBorder(null);
        but_salir.setBorderPainted(false);
        but_salir.setContentAreaFilled(false);
        but_salir.setFocusPainted(false);

        but_lacteos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/LACTEOS ICO.png"))); // NOI18N
        but_lacteos.setBorder(null);
        but_lacteos.setBorderPainted(false);
        but_lacteos.setContentAreaFilled(false);
        but_lacteos.setFocusPainted(false);
        but_lacteos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_lacteosActionPerformed(evt);
            }
        });

        but_otros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/OTROS ICO.png"))); // NOI18N
        but_otros.setBorder(null);
        but_otros.setBorderPainted(false);
        but_otros.setContentAreaFilled(false);
        but_otros.setFocusPainted(false);

        javax.swing.GroupLayout jEImagePanel2Layout = new javax.swing.GroupLayout(jEImagePanel2);
        jEImagePanel2.setLayout(jEImagePanel2Layout);
        jEImagePanel2Layout.setHorizontalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(but_salir))
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_granos)
                            .addComponent(but_verduras, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_frutas)
                            .addComponent(but_hierbas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_lacteos)
                            .addComponent(but_otros)
                            .addComponent(but_carrito))))
                .addGap(53, 53, 53))
        );
        jEImagePanel2Layout.setVerticalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEImagePanel2Layout.createSequentialGroup()
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_verduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_frutas)))
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(but_carrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(but_lacteos)))
                .addGap(116, 116, 116)
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_hierbas)
                    .addComponent(but_granos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_otros))
                .addGap(134, 134, 134)
                .addComponent(but_salir)
                .addGap(69, 69, 69))
        );

        jPanelRound1.add(jEImagePanel2);
        jEImagePanel2.setBounds(480, 0, 840, 700);

        getContentPane().add(jPanelRound1);
        jPanelRound1.setBounds(0, 0, 1320, 690);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void but_lacteosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_lacteosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_lacteosActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void but_verdurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_verdurasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_verdurasActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELARActionPerformed

    public JSpinner getContador() {
        return contador;
    }

    public void setContador(JSpinner contador) {
        this.contador = contador;
    }

    public JButton getCANCELAR() {
        return CANCELAR;
    }

    public void setCANCELAR(JButton CANCELAR) {
        this.CANCELAR = CANCELAR;
    }

    public JDialog getCARRITO() {
        return CARRITO;
    }

    public void setCARRITO(JDialog CARRITO) {
        this.CARRITO = CARRITO;
    }

    public JButton getComprar() {
        return comprar;
    }

    public void setComprar(JButton comprar) {
        this.comprar = comprar;
    }

    public JButton getDejarlo() {
        return dejarlo;
    }

    public void setDejarlo(JButton dejarlo) {
        this.dejarlo = dejarlo;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTablacarrito() {
        return tablacarrito;
    }

    public void setTablacarrito(JTable tablacarrito) {
        this.tablacarrito = tablacarrito;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    public JButton getSALIR() {
        return SALIR;
    }

    public void setSALIR(JButton SALIR) {
        this.SALIR = SALIR;
    }

    public JDialog getDlg_Productos() {
        return Dlg_Productos;
    }

    public void setDlg_Productos(JDialog Dlg_Productos) {
        this.Dlg_Productos = Dlg_Productos;
    }

    public JButton getBut_carrito() {
        return but_carrito;
    }

    public void setBut_carrito(JButton but_carrito) {
        this.but_carrito = but_carrito;
    }

    public JButton getBut_frutas() {
        return but_frutas;
    }

    public void setBut_frutas(JButton but_frutas) {
        this.but_frutas = but_frutas;
    }

    public JButton getBut_granos() {
        return but_granos;
    }

    public void setBut_granos(JButton but_granos) {
        this.but_granos = but_granos;
    }

    public JButton getBut_hierbas() {
        return but_hierbas;
    }

    public void setBut_hierbas(JButton but_hierbas) {
        this.but_hierbas = but_hierbas;
    }

    public JButton getBut_lacteos() {
        return but_lacteos;
    }

    public void setBut_lacteos(JButton but_lacteos) {
        this.but_lacteos = but_lacteos;
    }

    public JButton getBut_otros() {
        return but_otros;
    }

    public void setBut_otros(JButton but_otros) {
        this.but_otros = but_otros;
    }

    public JButton getBut_verduras() {
        return but_verduras;
    }

    public void setBut_verduras(JButton but_verduras) {
        this.but_verduras = but_verduras;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JSpinner getjSpinner1() {
        return jSpinner1;
    }

    public void setjSpinner1(JSpinner jSpinner1) {
        this.jSpinner1 = jSpinner1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JButton getBut_salir() {
        return but_salir;
    }

    public void setBut_salir(JButton but_salir) {
        this.but_salir = but_salir;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CANCELAR;
    public javax.swing.JDialog CARRITO;
    private javax.swing.JDialog Dlg_Productos;
    private javax.swing.JButton SALIR;
    public javax.swing.JButton but_carrito;
    private javax.swing.JButton but_frutas;
    private javax.swing.JButton but_granos;
    private javax.swing.JButton but_hierbas;
    private javax.swing.JButton but_lacteos;
    private javax.swing.JButton but_otros;
    private javax.swing.JButton but_salir;
    private javax.swing.JButton but_verduras;
    public javax.swing.JButton comprar;
    private javax.swing.JSpinner contador;
    public javax.swing.JButton dejarlo;
    private javax.swing.JButton jButton1;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTable tablacarrito;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//