// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;


public class Producto extends javax.swing.JFrame {

 
    public Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Productos = new javax.swing.JDialog();
        lb_tit_productos = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_descripcion = new javax.swing.JLabel();
        lb_existencia = new javax.swing.JLabel();
        lb_Eminima = new javax.swing.JLabel();
        lb_Emaxima = new javax.swing.JLabel();
        lb_precio = new javax.swing.JLabel();
        lb_provee = new javax.swing.JLabel();
        lb_categoria = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        cbx_codProvee = new javax.swing.JComboBox<>();
        crearproducto = new javax.swing.JButton();
        but_cancelar = new javax.swing.JButton();
        txt_categoria = new javax.swing.JComboBox<>();
        precio = new javax.swing.JSpinner();
        exi_max = new javax.swing.JSpinner();
        exi_min = new javax.swing.JSpinner();
        existencia = new javax.swing.JSpinner();
        txt_cod = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        txt_consulta = new javax.swing.JTextField();
        but_eliminar = new javax.swing.JButton();
        but_modificar = new javax.swing.JButton();
        but_crear = new javax.swing.JButton();
        but_refrescar = new javax.swing.JButton();
        but_limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rep_producto = new javax.swing.JTable();
        but_atras = new javax.swing.JButton();
        lb_tit_producto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Dlg_Productos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_tit_productos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_tit_productos.setForeground(new java.awt.Color(102, 0, 0));
        lb_tit_productos.setText("REGISTRO DE PRODUCTOS");
        Dlg_Productos.getContentPane().add(lb_tit_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 32, -1, -1));

        lb_codigo.setText("Código:");
        Dlg_Productos.getContentPane().add(lb_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        lb_nombre.setText("Nombre:");
        Dlg_Productos.getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        lb_descripcion.setText("Descripción:");
        Dlg_Productos.getContentPane().add(lb_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));

        lb_existencia.setText("Existencia:");
        Dlg_Productos.getContentPane().add(lb_existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        lb_Eminima.setText("Existencia_Minima:");
        Dlg_Productos.getContentPane().add(lb_Eminima, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        lb_Emaxima.setText("Existencia_Maxima:");
        Dlg_Productos.getContentPane().add(lb_Emaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        lb_precio.setText("Precio:");
        Dlg_Productos.getContentPane().add(lb_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 20));

        lb_provee.setText("Cod_Proveedor:");
        Dlg_Productos.getContentPane().add(lb_provee, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        lb_categoria.setText("Categoría:");
        Dlg_Productos.getContentPane().add(lb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 20));
        Dlg_Productos.getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 170, 190, -1));
        Dlg_Productos.getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 132, 190, -1));

        cbx_codProvee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));
        Dlg_Productos.getContentPane().add(cbx_codProvee, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 353, 190, -1));

        crearproducto.setText("CREAR");
        Dlg_Productos.getContentPane().add(crearproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 80, -1));

        but_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        but_cancelar.setText("Cancelar");
        Dlg_Productos.getContentPane().add(but_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        txt_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verduras", "Lacteos", "Frutas", "Granos", "Hierbas", "Otros" }));
        Dlg_Productos.getContentPane().add(txt_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 391, 190, -1));

        precio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.25d));
        Dlg_Productos.getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 322, 108, -1));

        exi_max.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
        Dlg_Productos.getContentPane().add(exi_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 284, 108, -1));

        exi_min.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
        Dlg_Productos.getContentPane().add(exi_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 246, 108, 20));

        existencia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
        Dlg_Productos.getContentPane().add(existencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 208, 108, -1));

        txt_cod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Dlg_Productos.getContentPane().add(txt_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 92, 190, 20));

        jButton1.setText("GENERAR");
        Dlg_Productos.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 91, -1, -1));

        EDITAR.setText("EDITAR");
        Dlg_Productos.getContentPane().add(EDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 80, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(685, 460));
        setPreferredSize(new java.awt.Dimension(685, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 163, -1));

        but_eliminar.setText("Eliminar");
        getContentPane().add(but_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        but_modificar.setText("Modificar");
        getContentPane().add(but_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        but_crear.setText("Crear");
        but_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_crearActionPerformed(evt);
            }
        });
        getContentPane().add(but_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        but_refrescar.setText("Refrescar");
        getContentPane().add(but_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        but_limpiar.setText("Limpiar");
        getContentPane().add(but_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 103, -1, -1));

        tbl_rep_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Existencias", "E_min", "E_max", "Precio", "Cod_proveedor", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tbl_rep_producto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 144, 587, 230));

        but_atras.setText("Atras");
        getContentPane().add(but_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 90, -1));

        lb_tit_producto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_tit_producto.setText("PRODUCTOS");
        getContentPane().add(lb_tit_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 21, -1, -1));

        jLabel1.setText("BUSCAR:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_crearActionPerformed

    public JButton getEDITAR() {
        return EDITAR;
    }

    public void setEDITAR(JButton EDITAR) {
        this.EDITAR = EDITAR;
    }

    public JDialog getDlg_Productos() {
        return Dlg_Productos;
    }

    public void setDlg_Productos(JDialog Dlg_Productos) {
        this.Dlg_Productos = Dlg_Productos;
    }

    public JButton getBut_atras() {
        return but_atras;
    }

    public void setBut_atras(JButton but_atras) {
        this.but_atras = but_atras;
    }

    public JButton getBut_cancelar() {
        return but_cancelar;
    }

    public void setBut_cancelar(JButton but_cancelar) {
        this.but_cancelar = but_cancelar;
    }

    public JButton getBut_crear() {
        return but_crear;
    }

    public void setBut_crear(JButton but_crear) {
        this.but_crear = but_crear;
    }

    public JButton getBut_eliminar() {
        return but_eliminar;
    }

    public void setBut_eliminar(JButton but_eliminar) {
        this.but_eliminar = but_eliminar;
    }

    public JButton getBut_limpiar() {
        return but_limpiar;
    }

    public void setBut_limpiar(JButton but_limpiar) {
        this.but_limpiar = but_limpiar;
    }

    public JButton getBut_modificar() {
        return but_modificar;
    }

    public void setBut_modificar(JButton but_modificar) {
        this.but_modificar = but_modificar;
    }

    public JButton getBut_refrescar() {
        return but_refrescar;
    }

    public void setBut_refrescar(JButton but_refrescar) {
        this.but_refrescar = but_refrescar;
    }

    public JComboBox<String> getCbx_codProvee() {
        return cbx_codProvee;
    }

    public void setCbx_codProvee(JComboBox<String> cbx_codProvee) {
        this.cbx_codProvee = cbx_codProvee;
    }

    public JButton getCrearproducto() {
        return crearproducto;
    }

    public void setCrearproducto(JButton crearproducto) {
        this.crearproducto = crearproducto;
    }

    public JSpinner getExi_max() {
        return exi_max;
    }

    public void setExi_max(JSpinner exi_max) {
        this.exi_max = exi_max;
    }

    public JSpinner getExi_min() {
        return exi_min;
    }

    public void setExi_min(JSpinner exi_min) {
        this.exi_min = exi_min;
    }

    public JSpinner getExistencia() {
        return existencia;
    }

    public void setExistencia(JSpinner existencia) {
        this.existencia = existencia;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLb_Emaxima() {
        return lb_Emaxima;
    }

    public void setLb_Emaxima(JLabel lb_Emaxima) {
        this.lb_Emaxima = lb_Emaxima;
    }

    public JLabel getLb_Eminima() {
        return lb_Eminima;
    }

    public void setLb_Eminima(JLabel lb_Eminima) {
        this.lb_Eminima = lb_Eminima;
    }

    public JLabel getLb_categoria() {
        return lb_categoria;
    }

    public void setLb_categoria(JLabel lb_categoria) {
        this.lb_categoria = lb_categoria;
    }

    public JLabel getLb_codigo() {
        return lb_codigo;
    }

    public void setLb_codigo(JLabel lb_codigo) {
        this.lb_codigo = lb_codigo;
    }

    public JLabel getLb_descripcion() {
        return lb_descripcion;
    }

    public void setLb_descripcion(JLabel lb_descripcion) {
        this.lb_descripcion = lb_descripcion;
    }

    public JLabel getLb_existencia() {
        return lb_existencia;
    }

    public void setLb_existencia(JLabel lb_existencia) {
        this.lb_existencia = lb_existencia;
    }

    public JLabel getLb_nombre() {
        return lb_nombre;
    }

    public void setLb_nombre(JLabel lb_nombre) {
        this.lb_nombre = lb_nombre;
    }

    public JLabel getLb_precio() {
        return lb_precio;
    }

    public void setLb_precio(JLabel lb_precio) {
        this.lb_precio = lb_precio;
    }

    public JLabel getLb_provee() {
        return lb_provee;
    }

    public void setLb_provee(JLabel lb_provee) {
        this.lb_provee = lb_provee;
    }

    public JLabel getLb_tit_producto() {
        return lb_tit_producto;
    }

    public void setLb_tit_producto(JLabel lb_tit_producto) {
        this.lb_tit_producto = lb_tit_producto;
    }

    public JLabel getLb_tit_productos() {
        return lb_tit_productos;
    }

    public void setLb_tit_productos(JLabel lb_tit_productos) {
        this.lb_tit_productos = lb_tit_productos;
    }

    public JLabel getTxt_cod() {
        return txt_cod;
    }

    public void setTxt_cod(JLabel ltxt_cod) {
        this.txt_cod = ltxt_cod;
    }

    public JSpinner getPrecio() {
        return precio;
    }

    public void setPrecio(JSpinner precio) {
        this.precio = precio;
    }

    public JTable getTbl_rep_producto() {
        return tbl_rep_producto;
    }

    public void setTbl_rep_producto(JTable tbl_rep_producto) {
        this.tbl_rep_producto = tbl_rep_producto;
    }

    public JComboBox<String> getTxt_categoria() {
        return txt_categoria;
    }

    public void setTxt_categoria(JComboBox<String> txt_categoria) {
        this.txt_categoria = txt_categoria;
    }

    public JTextField getTxt_consulta() {
        return txt_consulta;
    }

    public void setTxt_consulta(JTextField txt_consulta) {
        this.txt_consulta = txt_consulta;
    }

    public JTextField getTxt_descripcion() {
        return txt_descripcion;
    }

    public void setTxt_descripcion(JTextField txt_descripcion) {
        this.txt_descripcion = txt_descripcion;
    }

    public JTextField getTxt_nombre() {
        return txt_nombre;
    }

    public void setTxt_nombre(JTextField txt_nombre) {
        this.txt_nombre = txt_nombre;
    }

   

    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dlg_Productos;
    private javax.swing.JButton EDITAR;
    private javax.swing.JButton but_atras;
    private javax.swing.JButton but_cancelar;
    private javax.swing.JButton but_crear;
    private javax.swing.JButton but_eliminar;
    private javax.swing.JButton but_limpiar;
    private javax.swing.JButton but_modificar;
    private javax.swing.JButton but_refrescar;
    private javax.swing.JComboBox<String> cbx_codProvee;
    private javax.swing.JButton crearproducto;
    private javax.swing.JSpinner exi_max;
    private javax.swing.JSpinner exi_min;
    private javax.swing.JSpinner existencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Emaxima;
    private javax.swing.JLabel lb_Eminima;
    private javax.swing.JLabel lb_categoria;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_descripcion;
    private javax.swing.JLabel lb_existencia;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JLabel lb_provee;
    private javax.swing.JLabel lb_tit_producto;
    private javax.swing.JLabel lb_tit_productos;
    private javax.swing.JSpinner precio;
    private javax.swing.JTable tbl_rep_producto;
    private javax.swing.JComboBox<String> txt_categoria;
    private javax.swing.JLabel txt_cod;
    private javax.swing.JTextField txt_consulta;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//