// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
 
public class Proveedor extends javax.swing.JFrame {


    public Proveedor() {
        initComponents();
        txt_id.addKeyListener(new VALIDACIONES.Numeros());    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Proveedor = new javax.swing.JDialog();
        lb_tituloprov = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_nombres = new javax.swing.JLabel();
        lb_apellidos = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JLabel();
        lb_cuenta = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_numcuenta = new javax.swing.JTextField();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        but_aceptar = new javax.swing.JButton();
        but_cancelar = new javax.swing.JButton();
        DLG_GENERARCODIGO = new javax.swing.JButton();
        Txt_codifo = new javax.swing.JLabel();
        DLG_CREAROTRO = new javax.swing.JButton();
        but_modificar = new javax.swing.JButton();
        but_crear = new javax.swing.JButton();
        but_consultar = new javax.swing.JButton();
        but_limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rep_proveedor = new javax.swing.JTable();
        but_atras = new javax.swing.JButton();
        lb_tit_proveedor = new javax.swing.JLabel();
        txt_consulta = new javax.swing.JTextField();

        Dlg_Proveedor.setMinimumSize(new java.awt.Dimension(500, 500));
        Dlg_Proveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_tituloprov.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_tituloprov.setForeground(new java.awt.Color(102, 0, 0));
        lb_tituloprov.setText("REGISTRO DE PROVEEDOR");
        Dlg_Proveedor.getContentPane().add(lb_tituloprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 23, -1, -1));

        lb_id.setText("Id:");
        Dlg_Proveedor.getContentPane().add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 67, -1, -1));

        lb_nombres.setText("Nombres:");
        Dlg_Proveedor.getContentPane().add(lb_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 105, -1, -1));

        lb_apellidos.setText("Apellidos:");
        Dlg_Proveedor.getContentPane().add(lb_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 143, -1, -1));

        lb_telefono.setText("Teléfono:");
        Dlg_Proveedor.getContentPane().add(lb_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 181, -1, -1));

        lb_direccion.setText("Dirección:");
        Dlg_Proveedor.getContentPane().add(lb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 219, -1, -1));

        lb_fecha.setText("Fecha de nacimiento:");
        Dlg_Proveedor.getContentPane().add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 263, -1, -1));

        lb_codigo.setText("Cod_Proveedor:");
        Dlg_Proveedor.getContentPane().add(lb_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 295, -1, -1));

        lb_cuenta.setText("N° cuenta:");
        Dlg_Proveedor.getContentPane().add(lb_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 339, -1, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });
        Dlg_Proveedor.getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 64, 186, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        Dlg_Proveedor.getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 102, 186, -1));

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        Dlg_Proveedor.getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 257, -1));

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        Dlg_Proveedor.getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 178, 257, -1));

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });
        Dlg_Proveedor.getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 219, 256, -1));

        txt_numcuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numcuentaKeyTyped(evt);
            }
        });
        Dlg_Proveedor.getContentPane().add(txt_numcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 336, 190, -1));
        Dlg_Proveedor.getContentPane().add(dtcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, -1));

        but_aceptar.setText("Aceptar");
        Dlg_Proveedor.getContentPane().add(but_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        but_cancelar.setText("Cancelar");
        Dlg_Proveedor.getContentPane().add(but_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        DLG_GENERARCODIGO.setText("GENERAR");
        Dlg_Proveedor.getContentPane().add(DLG_GENERARCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 295, 90, -1));

        Txt_codifo.setBackground(new java.awt.Color(153, 153, 255));
        Txt_codifo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Dlg_Proveedor.getContentPane().add(Txt_codifo, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 295, 196, 23));

        DLG_CREAROTRO.setText("CREAR");
        Dlg_Proveedor.getContentPane().add(DLG_CREAROTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(667, 438));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        but_modificar.setText("Modificar");
        getContentPane().add(but_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 62, -1, -1));

        but_crear.setText("Crear");
        getContentPane().add(but_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 62, -1, -1));

        but_consultar.setText("Consultar:");
        getContentPane().add(but_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, -1, -1));

        but_limpiar.setText("Limpiar");
        getContentPane().add(but_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 103, -1, -1));

        tbl_rep_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "APELLIDO", "NOMBRE", "TELEFONO", "DIRECCION", "EDAD", "CEDULA", "NUMERO CUENTA"
            }
        ));
        jScrollPane1.setViewportView(tbl_rep_proveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 144, 587, 230));

        but_atras.setText("Atras");
        getContentPane().add(but_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 393, -1, -1));

        lb_tit_proveedor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_tit_proveedor.setText("PROVEEDORES");
        getContentPane().add(lb_tit_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 21, -1, -1));
        getContentPane().add(txt_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 63, 163, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        if(txt_id.getText().length()>=10){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        if(txt_nombre.getText().length()>=50){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 50 DIGITOS");
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        if(txt_apellido.getText().length()>=50){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 50 DIGITOS");
        }
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        if(txt_telefono.getText().length()>=10){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped
        if(txt_direccion.getText().length()>=50){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 50 DIGITOS");
        }
    }//GEN-LAST:event_txt_direccionKeyTyped

    private void txt_numcuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numcuentaKeyTyped
        if(txt_numcuenta.getText().length()>=10){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_txt_numcuentaKeyTyped

    public static JButton getDLG_CREAROTRO() {
        return DLG_CREAROTRO;
    }

    public static void setDLG_CREAROTRO(JButton DLG_CREAROTRO) {
        Proveedor.DLG_CREAROTRO = DLG_CREAROTRO;
    }

    public static JButton getDLG_GENERARCODIGO() {
        return DLG_GENERARCODIGO;
    }

    public static void setDLG_GENERARCODIGO(JButton DLG_GENERARCODIGO) {
        Proveedor.DLG_GENERARCODIGO = DLG_GENERARCODIGO;
    }

    public static JDialog getDlg_Proveedor() {
        return Dlg_Proveedor;
    }

    public static void setDlg_Proveedor(JDialog Dlg_Proveedor) {
        Proveedor.Dlg_Proveedor = Dlg_Proveedor;
    }

    public static JLabel getTxt_codifo() {
        return Txt_codifo;
    }

    public static void setTxt_codifo(JLabel Txt_codifo) {
        Proveedor.Txt_codifo = Txt_codifo;
    }

    public static JButton getBut_aceptar() {
        return but_aceptar;
    }

    public static void setBut_aceptar(JButton but_aceptar) {
        Proveedor.but_aceptar = but_aceptar;
    }

    public JButton getBut_atras() {
        return but_atras;
    }

    public void setBut_atras(JButton but_atras) {
        this.but_atras = but_atras;
    }

    public static JButton getBut_cancelar() {
        return but_cancelar;
    }

    public static void setBut_cancelar(JButton but_cancelar) {
        Proveedor.but_cancelar = but_cancelar;
    }

    public JButton getBut_consultar() {
        return but_consultar;
    }

    public void setBut_consultar(JButton but_consultar) {
        this.but_consultar = but_consultar;
    }

    public JButton getBut_crear() {
        return but_crear;
    }

    public void setBut_crear(JButton but_crear) {
        this.but_crear = but_crear;
    }

    public JButton getBut_limpiar() {
        return but_limpiar;
    }

    public void setBut_limpiar(JButton but_limpiar) {
        this.but_limpiar = but_limpiar;
    }

    public JButton getBut_modificar() {
        return but_modificar;
    }

    public void setBut_modificar(JButton but_modificar) {
        this.but_modificar = but_modificar;
    }

    public JDateChooser getDtcFechaNacimiento() {
        return dtcFechaNacimiento;
    }

    public void setDtcFechaNacimiento(JDateChooser dtcFechaNacimiento) {
        this.dtcFechaNacimiento = dtcFechaNacimiento;
    }

    public static JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public static void setjScrollPane1(JScrollPane jScrollPane1) {
        Proveedor.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLb_apellidos() {
        return lb_apellidos;
    }

    public void setLb_apellidos(JLabel lb_apellidos) {
        this.lb_apellidos = lb_apellidos;
    }

    public JLabel getLb_codigo() {
        return lb_codigo;
    }

    public void setLb_codigo(JLabel lb_codigo) {
        this.lb_codigo = lb_codigo;
    }

    public JLabel getLb_cuenta() {
        return lb_cuenta;
    }

    public void setLb_cuenta(JLabel lb_cuenta) {
        this.lb_cuenta = lb_cuenta;
    }

    public JLabel getLb_direccion() {
        return lb_direccion;
    }

    public void setLb_direccion(JLabel lb_direccion) {
        this.lb_direccion = lb_direccion;
    }

    public JLabel getLb_fecha() {
        return lb_fecha;
    }

    public void setLb_fecha(JLabel lb_fecha) {
        this.lb_fecha = lb_fecha;
    }

    public JLabel getLb_id() {
        return lb_id;
    }

    public void setLb_id(JLabel lb_id) {
        this.lb_id = lb_id;
    }

    public JLabel getLb_nombres() {
        return lb_nombres;
    }

    public void setLb_nombres(JLabel lb_nombres) {
        this.lb_nombres = lb_nombres;
    }

    public JLabel getLb_telefono() {
        return lb_telefono;
    }

    public void setLb_telefono(JLabel lb_telefono) {
        this.lb_telefono = lb_telefono;
    }

    public JLabel getLb_tit_proveedor() {
        return lb_tit_proveedor;
    }

    public void setLb_tit_proveedor(JLabel lb_tit_proveedor) {
        this.lb_tit_proveedor = lb_tit_proveedor;
    }

    public JLabel getLb_tituloprov() {
        return lb_tituloprov;
    }

    public void setLb_tituloprov(JLabel lb_tituloprov) {
        this.lb_tituloprov = lb_tituloprov;
    }

    public JTable getTbl_rep_proveedor() {
        return tbl_rep_proveedor;
    }

    public void setTbl_rep_proveedor(JTable tbl_rep_proveedor) {
        this.tbl_rep_proveedor = tbl_rep_proveedor;
    }

    public JTextField getTxt_apellido() {
        return txt_apellido;
    }

    public void setTxt_apellido(JTextField txt_apellido) {
        this.txt_apellido = txt_apellido;
    }

    public static JTextField getTxt_consulta() {
        return txt_consulta;
    }

    public static void setTxt_consulta(JTextField txt_consulta) {
        Proveedor.txt_consulta = txt_consulta;
    }

    public JTextField getTxt_direccion() {
        return txt_direccion;
    }

    public void setTxt_direccion(JTextField txt_direccion) {
        this.txt_direccion = txt_direccion;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nombre() {
        return txt_nombre;
    }

    public void setTxt_nombre(JTextField txt_nombre) {
        this.txt_nombre = txt_nombre;
    }

    public JTextField getTxt_numcuenta() {
        return txt_numcuenta;
    }

    public void setTxt_numcuenta(JTextField txt_numcuenta) {
        this.txt_numcuenta = txt_numcuenta;
    }

    public JTextField getTxt_telefono() {
        return txt_telefono;
    }

    public void setTxt_telefono(JTextField txt_telefono) {
        this.txt_telefono = txt_telefono;
    }

   
 
    
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton DLG_CREAROTRO;
    public static javax.swing.JButton DLG_GENERARCODIGO;
    public static javax.swing.JDialog Dlg_Proveedor;
    public static javax.swing.JLabel Txt_codifo;
    public static javax.swing.JButton but_aceptar;
    private javax.swing.JButton but_atras;
    public static javax.swing.JButton but_cancelar;
    private javax.swing.JButton but_consultar;
    private javax.swing.JButton but_crear;
    private javax.swing.JButton but_limpiar;
    private javax.swing.JButton but_modificar;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_apellidos;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_cuenta;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JLabel lb_tit_proveedor;
    private javax.swing.JLabel lb_tituloprov;
    private javax.swing.JTable tbl_rep_proveedor;
    private javax.swing.JTextField txt_apellido;
    public static javax.swing.JTextField txt_consulta;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numcuenta;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//