// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

public class Recepcion extends javax.swing.JFrame {

 
    public Recepcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mcontraseña = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        salir1 = new javax.swing.JButton();
        visual = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        musuario = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        clientes = new javax.swing.JButton();
        cajeros = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Usuario");
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));

        jLabel3.setText("Contraceña");
        jDialog1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 20));
        jDialog1.getContentPane().add(mcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 99, 164, 23));

        ingresar.setText("INGRESAR");
        jDialog1.getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        salir1.setText("SALIR");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 157, -1, -1));

        visual.setText("0");
        jDialog1.getContentPane().add(visual, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 99, -1, -1));

        jScrollPane2.setViewportView(musuario);

        jDialog1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 55, 164, -1));

        jLabel1.setBackground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("LOGIN");
        jDialog1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 11, 74, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setText("RECEPCION");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 83, 24));

        clientes.setText("CLIENTES");
        getContentPane().add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 73, 110, 31));

        cajeros.setText("CAJEROS");
        getContentPane().add(cajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 31));

        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 131, 81, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salir1ActionPerformed

    public JButton getIngresar() {
        return ingresar;
    }

    public void setIngresar(JButton ingresar) {
        this.ingresar = ingresar;
    }

    public JDialog getjDialog1() {
        return jDialog1;
    }

    public void setjDialog1(JDialog jDialog1) {
        this.jDialog1 = jDialog1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JPasswordField getMcontraseña() {
        return mcontraseña;
    }

    public void setMcontraseña(JPasswordField mcontraseña) {
        this.mcontraseña = mcontraseña;
    }

    public JTextPane getMusuario() {
        return musuario;
    }

    public void setMusuario(JTextPane musuario) {
        this.musuario = musuario;
    }

    public JButton getSalir1() {
        return salir1;
    }

    public void setSalir1(JButton salir1) {
        this.salir1 = salir1;
    }

    public JButton getVisual() {
        return visual;
    }

    public void setVisual(JButton visual) {
        this.visual = visual;
    }

    public JButton getCajeros() {
        return cajeros;
    }

    public void setCajeros(JButton cajeros) {
        this.cajeros = cajeros;
    }

    public JButton getClientes() {
        return clientes;
    }

    public void setClientes(JButton clientes) {
        this.clientes = clientes;
    }

    public JButton getSalir() {
        return salir;
    }

    public void setSalir(JButton salir) {
        this.salir = salir;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }
 
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cajeros;
    private javax.swing.JButton clientes;
    private javax.swing.JButton ingresar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField mcontraseña;
    private javax.swing.JTextPane musuario;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton visual;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//