// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import LIB.FSTexFieldMD;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

public class Vista_proveedor extends javax.swing.JFrame {

    public Vista_proveedor() {
        initComponents();
        Vista_proveedor.this.setBackground(new Color(0, 0, 0, 0));
        Dlg_Proveedor.setLocationRelativeTo(null);
        txt_id.addKeyListener(new VALIDACIONES.Numeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Proveedor = new javax.swing.JDialog();
        paneldefondo = new javax.swing.JPanel();
        lb_tituloprov = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_nombres = new javax.swing.JLabel();
        lb_apellidos = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        lb_cuenta = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_numcuenta = new javax.swing.JTextField();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        DLG_GENERARCODIGO = new javax.swing.JButton();
        Txt_codifo = new javax.swing.JLabel();
        DLG_CREAROTRO = new javax.swing.JButton();
        but_aceptar = new javax.swing.JButton();
        but_cancelar = new javax.swing.JButton();
        jPanelRound1 = new LIB.JPanelRound();
        jEImagePanel2 = new LIB.JEImagePanel();
        but_limpiar = new javax.swing.JButton();
        txt_consulta = new LIB.FSTexFieldMD();
        but_crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rep_proveedor = new javax.swing.JTable();
        but_modificar = new javax.swing.JButton();
        but_atras = new javax.swing.JButton();
        but_refrescar = new javax.swing.JButton();
        jEImagePanel1 = new LIB.JEImagePanel();

        Dlg_Proveedor.setMinimumSize(new java.awt.Dimension(480, 580));
        Dlg_Proveedor.setPreferredSize(new java.awt.Dimension(480, 580));
        Dlg_Proveedor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneldefondo.setBackground(new java.awt.Color(255, 255, 204));
        paneldefondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_tituloprov.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_tituloprov.setForeground(new java.awt.Color(102, 0, 0));
        lb_tituloprov.setText("REGISTRO DE PROVEEDOR");
        paneldefondo.add(lb_tituloprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 23, -1, -1));

        lb_id.setText("Id:");
        paneldefondo.add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 67, -1, -1));

        lb_nombres.setText("Nombres:");
        paneldefondo.add(lb_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 105, -1, -1));

        lb_apellidos.setText("Apellidos:");
        paneldefondo.add(lb_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 143, -1, -1));

        lb_telefono.setText("Teléfono:");
        paneldefondo.add(lb_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 181, -1, -1));

        lb_direccion.setText("Dirección:");
        paneldefondo.add(lb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 219, -1, -1));

        lb_fecha.setText("Fecha de nacimiento:");
        paneldefondo.add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 263, -1, -1));

        lb_codigo.setText("Cod_Proveedor:");
        paneldefondo.add(lb_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 295, -1, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });
        paneldefondo.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 64, 186, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        paneldefondo.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 102, 186, -1));

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        paneldefondo.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 257, -1));

        lb_cuenta.setText("N° cuenta:");
        paneldefondo.add(lb_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 339, -1, -1));

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        paneldefondo.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 178, 257, -1));

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });
        paneldefondo.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 219, 256, -1));

        txt_numcuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numcuentaKeyTyped(evt);
            }
        });
        paneldefondo.add(txt_numcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 336, 190, -1));
        paneldefondo.add(dtcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, -1));

        DLG_GENERARCODIGO.setText("GENERAR");
        paneldefondo.add(DLG_GENERARCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 295, 90, -1));

        Txt_codifo.setBackground(new java.awt.Color(153, 153, 255));
        Txt_codifo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Txt_codifo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneldefondo.add(Txt_codifo, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 295, 196, 23));

        DLG_CREAROTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/CREAR ICO 2.png"))); // NOI18N
        DLG_CREAROTRO.setBorder(null);
        DLG_CREAROTRO.setBorderPainted(false);
        DLG_CREAROTRO.setContentAreaFilled(false);
        DLG_CREAROTRO.setFocusPainted(false);
        DLG_CREAROTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DLG_CREAROTROActionPerformed(evt);
            }
        });
        paneldefondo.add(DLG_CREAROTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        but_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ACTUALIZAR 2 ICO.png"))); // NOI18N
        but_aceptar.setBorder(null);
        but_aceptar.setBorderPainted(false);
        but_aceptar.setContentAreaFilled(false);
        but_aceptar.setFocusPainted(false);
        paneldefondo.add(but_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 180, -1));

        but_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_cancelar.setBorder(null);
        but_cancelar.setBorderPainted(false);
        but_cancelar.setContentAreaFilled(false);
        but_cancelar.setFocusPainted(false);
        paneldefondo.add(but_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        Dlg_Proveedor.getContentPane().add(paneldefondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 540));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1355, 670));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/recepcion.png"))); // NOI18N
        jEImagePanel2.setLayout(null);

        but_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/LIMPIAR ICO.png"))); // NOI18N
        but_limpiar.setBorder(null);
        but_limpiar.setBorderPainted(false);
        but_limpiar.setContentAreaFilled(false);
        but_limpiar.setFocusPainted(false);
        jEImagePanel2.add(but_limpiar);
        but_limpiar.setBounds(670, 140, 170, 50);

        txt_consulta.setForeground(new java.awt.Color(0, 0, 0));
        txt_consulta.setBordeColorFocus(new java.awt.Color(0, 102, 51));
        txt_consulta.setColorTransparente(true);
        txt_consulta.setPlaceholder("Buscar...");
        jEImagePanel2.add(txt_consulta);
        txt_consulta.setBounds(220, 140, 220, 50);

        but_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/CREAR ICO 2.png"))); // NOI18N
        but_crear.setBorder(null);
        but_crear.setBorderPainted(false);
        but_crear.setContentAreaFilled(false);
        but_crear.setFocusPainted(false);
        jEImagePanel2.add(but_crear);
        but_crear.setBounds(480, 70, 180, 50);

        tbl_rep_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "APELLIDO", "NOMBRE", "TELEFONO", "DIRECCION", "EDAD", "CEDULA", "NUMERO CUENTA"
            }
        ));
        jScrollPane1.setViewportView(tbl_rep_proveedor);

        jEImagePanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 230, 830, 320);

        but_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/MODIFICAR ICO.png"))); // NOI18N
        but_modificar.setBorder(null);
        but_modificar.setBorderPainted(false);
        but_modificar.setContentAreaFilled(false);
        but_modificar.setFocusPainted(false);
        jEImagePanel2.add(but_modificar);
        but_modificar.setBounds(490, 140, 170, 50);

        but_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_atras.setBorder(null);
        but_atras.setBorderPainted(false);
        but_atras.setContentAreaFilled(false);
        but_atras.setFocusPainted(false);
        jEImagePanel2.add(but_atras);
        but_atras.setBounds(630, 560, 180, 60);

        but_refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ACTUALIZAR ICO.png"))); // NOI18N
        but_refrescar.setBorderPainted(false);
        but_refrescar.setContentAreaFilled(false);
        but_refrescar.setFocusPainted(false);
        jEImagePanel2.add(but_refrescar);
        but_refrescar.setBounds(110, 140, 50, 50);

        jPanelRound1.add(jEImagePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 1090, 750));

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/proveedores.png"))); // NOI18N
        jPanelRound1.add(jEImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 750));

        getContentPane().add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        if (txt_id.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        if (txt_nombre.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 50 DIGITOS");
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        if (txt_apellido.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 50 DIGITOS");
        }
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        if (txt_telefono.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped
        if (txt_direccion.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 50 DIGITOS");
        }
    }//GEN-LAST:event_txt_direccionKeyTyped

    private void txt_numcuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numcuentaKeyTyped
        if (txt_numcuenta.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_txt_numcuentaKeyTyped

    private void DLG_CREAROTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DLG_CREAROTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DLG_CREAROTROActionPerformed

    public JButton getDLG_CREAROTRO() {
        return DLG_CREAROTRO;
    }

    public void setDLG_CREAROTRO(JButton DLG_CREAROTRO) {
        this.DLG_CREAROTRO = DLG_CREAROTRO;
    }

    public JButton getBut_aceptar() {
        return but_aceptar;
    }

    public void setBut_aceptar(JButton but_aceptar) {
        this.but_aceptar = but_aceptar;
    }

    public JButton getBut_cancelar() {
        return but_cancelar;
    }

    public void setBut_cancelar(JButton but_cancelar) {
        this.but_cancelar = but_cancelar;
    }

    
    
    
    
    
    public JButton getBut_refrescar() {
        return but_refrescar;
    }

    public void setBut_refrescar(JButton but_refrescar) {
        this.but_refrescar = but_refrescar;
    }

    public JPanel getPaneldefondo() {
        return paneldefondo;
    }

    public void setPaneldefondo(JPanel paneldefondo) {
        this.paneldefondo = paneldefondo;
    }

    public static JButton getDLG_GENERARCODIGO() {
        return DLG_GENERARCODIGO;
    }

    public static void setDLG_GENERARCODIGO(JButton DLG_GENERARCODIGO) {
        Vista_proveedor.DLG_GENERARCODIGO = DLG_GENERARCODIGO;
    }

    public static JDialog getDlg_Proveedor() {
        return Dlg_Proveedor;
    }

    public static void setDlg_Proveedor(JDialog Dlg_Proveedor) {
        Vista_proveedor.Dlg_Proveedor = Dlg_Proveedor;
    }

    public static JLabel getTxt_codifo() {
        return Txt_codifo;
    }

    public static void setTxt_codifo(JLabel Txt_codifo) {
        Vista_proveedor.Txt_codifo = Txt_codifo;
    }

 

    public JButton getBut_atras() {
        return but_atras;
    }

    public void setBut_atras(JButton but_atras) {
        this.but_atras = but_atras;
    }

   

    public JButton getBut_crear() {
        return but_crear;
    }

    public void setBut_crear(JButton but_crear) {
        this.but_crear = but_crear;
    }

    public JButton getBut_limpiar() {
        return but_limpiar;
    }

    public void setBut_limpiar(JButton but_limpiar) {
        this.but_limpiar = but_limpiar;
    }

    public JButton getBut_modificar() {
        return but_modificar;
    }

    public void setBut_modificar(JButton but_modificar) {
        this.but_modificar = but_modificar;
    }

    public JDateChooser getDtcFechaNacimiento() {
        return dtcFechaNacimiento;
    }

    public void setDtcFechaNacimiento(JDateChooser dtcFechaNacimiento) {
        this.dtcFechaNacimiento = dtcFechaNacimiento;
    }

    public static JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public static void setjScrollPane1(JScrollPane jScrollPane1) {
        Vista_proveedor.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLb_apellidos() {
        return lb_apellidos;
    }

    public void setLb_apellidos(JLabel lb_apellidos) {
        this.lb_apellidos = lb_apellidos;
    }

    public JLabel getLb_codigo() {
        return lb_codigo;
    }

    public void setLb_codigo(JLabel lb_codigo) {
        this.lb_codigo = lb_codigo;
    }

    public JLabel getLb_cuenta() {
        return lb_cuenta;
    }

    public void setLb_cuenta(JLabel lb_cuenta) {
        this.lb_cuenta = lb_cuenta;
    }

    public JLabel getLb_direccion() {
        return lb_direccion;
    }

    public void setLb_direccion(JLabel lb_direccion) {
        this.lb_direccion = lb_direccion;
    }

    public JLabel getLb_fecha() {
        return lb_fecha;
    }

    public void setLb_fecha(JLabel lb_fecha) {
        this.lb_fecha = lb_fecha;
    }

    public JLabel getLb_id() {
        return lb_id;
    }

    public void setLb_id(JLabel lb_id) {
        this.lb_id = lb_id;
    }

    public JLabel getLb_nombres() {
        return lb_nombres;
    }

    public void setLb_nombres(JLabel lb_nombres) {
        this.lb_nombres = lb_nombres;
    }

    public JLabel getLb_telefono() {
        return lb_telefono;
    }

    public void setLb_telefono(JLabel lb_telefono) {
        this.lb_telefono = lb_telefono;
    }

    public JLabel getLb_tituloprov() {
        return lb_tituloprov;
    }

    public void setLb_tituloprov(JLabel lb_tituloprov) {
        this.lb_tituloprov = lb_tituloprov;
    }

    public JTable getTbl_rep_proveedor() {
        return tbl_rep_proveedor;
    }

    public void setTbl_rep_proveedor(JTable tbl_rep_proveedor) {
        this.tbl_rep_proveedor = tbl_rep_proveedor;
    }

    public JTextField getTxt_apellido() {
        return txt_apellido;
    }

    public void setTxt_apellido(JTextField txt_apellido) {
        this.txt_apellido = txt_apellido;
    }

    public JTextField getTxt_direccion() {
        return txt_direccion;
    }

    public void setTxt_direccion(JTextField txt_direccion) {
        this.txt_direccion = txt_direccion;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nombre() {
        return txt_nombre;
    }

    public void setTxt_nombre(JTextField txt_nombre) {
        this.txt_nombre = txt_nombre;
    }

    public JTextField getTxt_numcuenta() {
        return txt_numcuenta;
    }

    public void setTxt_numcuenta(JTextField txt_numcuenta) {
        this.txt_numcuenta = txt_numcuenta;
    }

    public JTextField getTxt_telefono() {
        return txt_telefono;
    }

    public void setTxt_telefono(JTextField txt_telefono) {
        this.txt_telefono = txt_telefono;
    }

  

    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////

    public FSTexFieldMD getTxt_consulta() {
        return txt_consulta;
    }

    public void setTxt_consulta(FSTexFieldMD txt_consulta) {
        this.txt_consulta = txt_consulta;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DLG_CREAROTRO;
    public static javax.swing.JButton DLG_GENERARCODIGO;
    public static javax.swing.JDialog Dlg_Proveedor;
    public static javax.swing.JLabel Txt_codifo;
    private javax.swing.JButton but_aceptar;
    private javax.swing.JButton but_atras;
    private javax.swing.JButton but_cancelar;
    private javax.swing.JButton but_crear;
    private javax.swing.JButton but_limpiar;
    private javax.swing.JButton but_modificar;
    private javax.swing.JButton but_refrescar;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private LIB.JPanelRound jPanelRound1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_apellidos;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_cuenta;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JLabel lb_tituloprov;
    private javax.swing.JPanel paneldefondo;
    private javax.swing.JTable tbl_rep_proveedor;
    private javax.swing.JTextField txt_apellido;
    private LIB.FSTexFieldMD txt_consulta;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numcuenta;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
