// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import LIB.FSTexFieldMD;
import LIB.JEImagePanel;
import LIB.JPanelRound;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class Vista_factura extends javax.swing.JFrame {

 
    public Vista_factura() {
        initComponents();
        Vista_factura.this.setBackground(new Color(0, 0, 0, 0));
        buscadetalle.addKeyListener(new VALIDACIONES.Numeros());
        buscacabeza.addKeyListener(new VALIDACIONES.Numeros());
setIconImage(new ImageIcon(getClass().getResource("/ICONOS/iconocolibrie.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dlg_Factura = new javax.swing.JDialog();
        lb_factura = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        lb_numfac = new javax.swing.JLabel();
        lb_facnumero = new javax.swing.JLabel();
        lb_nacimiento = new javax.swing.JLabel();
        lb_cedula = new javax.swing.JLabel();
        lb_nombres = new javax.swing.JLabel();
        lb_apellidos = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        lb_fechanac = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        lb_total = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jPanelRound2 = new LIB.JPanelRound();
        jEImagePanel3 = new LIB.JEImagePanel();
        lb_dia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_fac = new javax.swing.JTable();
        but_cancelar = new javax.swing.JButton();
        but_actualizar = new javax.swing.JButton();
        jPanelRound1 = new LIB.JPanelRound();
        jEImagePanel1 = new LIB.JEImagePanel();
        jEImagePanel2 = new LIB.JEImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cabezafactura = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        but_consultar = new javax.swing.JButton();
        but_limpiar = new javax.swing.JButton();
        but_atras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscacabeza = new LIB.FSTexFieldMD();
        buscadetalle = new LIB.FSTexFieldMD();
        facturasjasper = new javax.swing.JButton();

        Dlg_Factura.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_factura.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_factura.setForeground(new java.awt.Color(0, 153, 51));
        lb_factura.setText("FACTURA");
        Dlg_Factura.getContentPane().add(lb_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        lb_logo.setText("jLabel2");
        Dlg_Factura.getContentPane().add(lb_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        lb_numfac.setText("Factura N°:");
        Dlg_Factura.getContentPane().add(lb_numfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, -1, -1));
        Dlg_Factura.getContentPane().add(lb_facnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 133, 16));

        lb_nacimiento.setText("Fecha:");
        Dlg_Factura.getContentPane().add(lb_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        lb_cedula.setText("Cedula:");
        Dlg_Factura.getContentPane().add(lb_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        lb_nombres.setText("Nombres:");
        Dlg_Factura.getContentPane().add(lb_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        lb_apellidos.setText("Apellidos:");
        Dlg_Factura.getContentPane().add(lb_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        lb_telefono.setText("Teléfono:");
        Dlg_Factura.getContentPane().add(lb_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, -1));

        lb_fechanac.setText("Fecha_Nac:");
        Dlg_Factura.getContentPane().add(lb_fechanac, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, -1, -1));

        lb_direccion.setText("Direccion:");
        Dlg_Factura.getContentPane().add(lb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });
        Dlg_Factura.getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 130, -1));

        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });
        Dlg_Factura.getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 130, -1));
        Dlg_Factura.getContentPane().add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 129, -1));
        Dlg_Factura.getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 129, -1));
        Dlg_Factura.getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 130, 30));

        lb_total.setText("Total a Pagar:");
        Dlg_Factura.getContentPane().add(lb_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, -1, -1));

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        Dlg_Factura.getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 600, 63, -1));

        jPanelRound2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound2.setToolTipText("");
        jPanelRound2.setOpaque(true);
        jPanelRound2.setLayout(null);

        jEImagePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Facturas_1.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel3Layout = new javax.swing.GroupLayout(jEImagePanel3);
        jEImagePanel3.setLayout(jEImagePanel3Layout);
        jEImagePanel3Layout.setHorizontalGroup(
            jEImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jEImagePanel3Layout.setVerticalGroup(
            jEImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        jPanelRound2.add(jEImagePanel3);
        jEImagePanel3.setBounds(0, 0, 500, 710);
        jPanelRound2.add(lb_dia);
        lb_dia.setBounds(900, 100, 133, 14);

        table_fac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_fac);

        jPanelRound2.add(jScrollPane2);
        jScrollPane2.setBounds(540, 330, 670, 241);

        but_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_cancelar.setBorder(null);
        but_cancelar.setBorderPainted(false);
        but_cancelar.setContentAreaFilled(false);
        but_cancelar.setDefaultCapable(false);
        but_cancelar.setFocusPainted(false);
        jPanelRound2.add(but_cancelar);
        but_cancelar.setBounds(1060, 640, 180, 60);

        but_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ACTUALIZAR 2 ICO.png"))); // NOI18N
        but_actualizar.setBorder(null);
        but_actualizar.setBorderPainted(false);
        but_actualizar.setContentAreaFilled(false);
        but_actualizar.setFocusPainted(false);
        jPanelRound2.add(but_actualizar);
        but_actualizar.setBounds(540, 620, 165, 50);

        Dlg_Factura.getContentPane().add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 710));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1310, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(null);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FACTURAS.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanelRound1.add(jEImagePanel1);
        jEImagePanel1.setBounds(0, 0, 520, 730);

        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/recepcion.png"))); // NOI18N

        jLabel1.setText("CABEZA   FACTURAS");

        cabezafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NUMERO", "CODIGO", "CODIGO CLIENTE", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(cabezafactura);

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "COD_DETALLE", "COD_ENCABEZADO", "COD_PRODUCTO", "CANTIDAD", "PRECIO_FINAL"
            }
        ));
        jScrollPane1.setViewportView(tabladetalles);

        jLabel2.setText("DETALLE   FACTURA");

        jLabel4.setText("DETALLES");

        but_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/BUSCAR ICO.png"))); // NOI18N
        but_consultar.setBorder(null);
        but_consultar.setBorderPainted(false);
        but_consultar.setContentAreaFilled(false);
        but_consultar.setFocusPainted(false);

        but_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/LIMPIAR ICO.png"))); // NOI18N
        but_limpiar.setBorder(null);
        but_limpiar.setContentAreaFilled(false);
        but_limpiar.setDefaultCapable(false);
        but_limpiar.setFocusPainted(false);

        but_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_atras.setBorder(null);
        but_atras.setBorderPainted(false);
        but_atras.setContentAreaFilled(false);
        but_atras.setFocusPainted(false);

        jLabel3.setText("CABEZAS");

        buscacabeza.setForeground(new java.awt.Color(0, 0, 0));
        buscacabeza.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        buscacabeza.setColorTransparente(true);
        buscacabeza.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        buscacabeza.setPlaceholder("CODIGO FACTURA - CODIGO CLIENTE");
        buscacabeza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscacabezaKeyTyped(evt);
            }
        });

        buscadetalle.setForeground(new java.awt.Color(0, 0, 0));
        buscadetalle.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        buscadetalle.setColorTransparente(true);
        buscadetalle.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        buscadetalle.setPlaceholder("COD.CABEZA - COD.DETALLE - COD.PRODUCTO");
        buscadetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscadetalleKeyTyped(evt);
            }
        });

        facturasjasper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/IMPRIMIR ICO.png"))); // NOI18N
        facturasjasper.setBorder(null);
        facturasjasper.setBorderPainted(false);
        facturasjasper.setContentAreaFilled(false);
        facturasjasper.setFocusPainted(false);

        javax.swing.GroupLayout jEImagePanel2Layout = new javax.swing.GroupLayout(jEImagePanel2);
        jEImagePanel2.setLayout(jEImagePanel2Layout);
        jEImagePanel2Layout.setHorizontalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(but_atras)
                    .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jEImagePanel2Layout.createSequentialGroup()
                            .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buscacabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buscadetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(82, 82, 82)
                            .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jEImagePanel2Layout.createSequentialGroup()
                                    .addComponent(but_consultar)
                                    .addGap(34, 34, 34)
                                    .addComponent(but_limpiar))
                                .addComponent(facturasjasper))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jEImagePanel2Layout.setVerticalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addComponent(buscacabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscadetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jEImagePanel2Layout.createSequentialGroup()
                        .addGroup(jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEImagePanel2Layout.createSequentialGroup()
                                .addComponent(but_consultar)
                                .addGap(18, 18, 18)
                                .addComponent(facturasjasper))
                            .addComponent(but_limpiar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(but_atras)
                .addGap(38, 38, 38))
        );

        jPanelRound1.add(jEImagePanel2);
        jEImagePanel2.setBounds(520, 0, 800, 720);

        getContentPane().add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void buscacabezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscacabezaKeyTyped
        if (buscacabeza.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_buscacabezaKeyTyped

    private void buscadetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadetalleKeyTyped
        if (buscadetalle.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_buscadetalleKeyTyped

    public JButton getFacturasjasper() {
        return facturasjasper;
    }

    public void setFacturasjasper(JButton facturasjasper) {
        this.facturasjasper = facturasjasper;
    }

    
    
    public JDialog getDlg_Factura() {
        return Dlg_Factura;
    }
    public void setDlg_Factura(JDialog Dlg_Factura) {
        this.Dlg_Factura = Dlg_Factura;
    }
    public JButton getBut_actualizar() {
        return but_actualizar;
    }
    public void setBut_actualizar(JButton but_actualizar) {
        this.but_actualizar = but_actualizar;
    }
    public JButton getBut_atras() {
        return but_atras;
    }
    public void setBut_atras(JButton but_atras) {
        this.but_atras = but_atras;
    }
    public JButton getBut_cancelar() {
        return but_cancelar;
    }
    public void setBut_cancelar(JButton but_cancelar) {
        this.but_cancelar = but_cancelar;
    }
  
 
    public JButton getBut_limpiar() {
        return but_limpiar;
    }
    public void setBut_limpiar(JButton but_limpiar) {
        this.but_limpiar = but_limpiar;
    }
 
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }
    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }
    public JLabel getLb_apellidos() {
        return lb_apellidos;
    }
    public void setLb_apellidos(JLabel lb_apellidos) {
        this.lb_apellidos = lb_apellidos;
    }
    public JLabel getLb_cedula() {
        return lb_cedula;
    }
    public void setLb_cedula(JLabel lb_cedula) {
        this.lb_cedula = lb_cedula;
    }
    public JLabel getLb_dia() {
        return lb_dia;
    }
    public void setLb_dia(JLabel lb_dia) {
        this.lb_dia = lb_dia;
    }
    public JLabel getLb_direccion() {
        return lb_direccion;
    }
    public void setLb_direccion(JLabel lb_direccion) {
        this.lb_direccion = lb_direccion;
    }
    public JLabel getLb_facnumero() {
        return lb_facnumero;
    }
    public void setLb_facnumero(JLabel lb_facnumero) {
        this.lb_facnumero = lb_facnumero;
    }
    public JLabel getLb_factura() {
        return lb_factura;
    }
    public void setLb_factura(JLabel lb_factura) {
        this.lb_factura = lb_factura;
    }
    public JLabel getLb_fechanac() {
        return lb_fechanac;
    }
    public void setLb_fechanac(JLabel lb_fechanac) {
        this.lb_fechanac = lb_fechanac;
    }
    public JLabel getLb_logo() {
        return lb_logo;
    }
    public void setLb_logo(JLabel lb_logo) {
        this.lb_logo = lb_logo;
    }
    public JLabel getLb_nacimiento() {
        return lb_nacimiento;
    }
    public void setLb_nacimiento(JLabel lb_nacimiento) {
        this.lb_nacimiento = lb_nacimiento;
    }
    public JLabel getLb_nombres() {
        return lb_nombres;
    }
    public void setLb_nombres(JLabel lb_nombres) {
        this.lb_nombres = lb_nombres;
    }
    public JLabel getLb_numfac() {
        return lb_numfac;
    }
    public void setLb_numfac(JLabel lb_numfac) {
        this.lb_numfac = lb_numfac;
    }
    public JLabel getLb_telefono() {
        return lb_telefono;
    }
    public void setLb_telefono(JLabel lb_telefono) {
        this.lb_telefono = lb_telefono;
    }
   
    public JLabel getLb_total() {
        return lb_total;
    }
    public void setLb_total(JLabel lb_total) {
        this.lb_total = lb_total;
    }
    public JTable getTable_fac() {
        return table_fac;
    }
    public void setTable_fac(JTable table_fac) {
        this.table_fac = table_fac;
    }

    public JTextField getTxt_apellidos() {
        return txt_apellidos;
    }
    public void setTxt_apellidos(JTextField txt_apellidos) {
        this.txt_apellidos = txt_apellidos;
    }
    public JTextField getTxt_cedula() {
        return txt_cedula;
    }
    public void setTxt_cedula(JTextField txt_cedula) {
        this.txt_cedula = txt_cedula;
    }

    public FSTexFieldMD getBuscacabeza() {
        return buscacabeza;
    }

    public void setBuscacabeza(FSTexFieldMD buscacabeza) {
        this.buscacabeza = buscacabeza;
    }

    public FSTexFieldMD getBuscadetalle() {
        return buscadetalle;
    }

    public void setBuscadetalle(FSTexFieldMD buscadetalle) {
        this.buscadetalle = buscadetalle;
    }

    public JTable getCabezafactura() {
        return cabezafactura;
    }

    public void setCabezafactura(JTable cabezafactura) {
        this.cabezafactura = cabezafactura;
    }

    public JEImagePanel getjEImagePanel1() {
        return jEImagePanel1;
    }

    public void setjEImagePanel1(JEImagePanel jEImagePanel1) {
        this.jEImagePanel1 = jEImagePanel1;
    }

    public JEImagePanel getjEImagePanel2() {
        return jEImagePanel2;
    }

    public void setjEImagePanel2(JEImagePanel jEImagePanel2) {
        this.jEImagePanel2 = jEImagePanel2;
    }

    public JEImagePanel getjEImagePanel3() {
        return jEImagePanel3;
    }

    public void setjEImagePanel3(JEImagePanel jEImagePanel3) {
        this.jEImagePanel3 = jEImagePanel3;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JPanelRound getjPanelRound1() {
        return jPanelRound1;
    }

    public void setjPanelRound1(JPanelRound jPanelRound1) {
        this.jPanelRound1 = jPanelRound1;
    }

    public JPanelRound getjPanelRound2() {
        return jPanelRound2;
    }

    public void setjPanelRound2(JPanelRound jPanelRound2) {
        this.jPanelRound2 = jPanelRound2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JTable getTabladetalles() {
        return tabladetalles;
    }

    public void setTabladetalles(JTable tabladetalles) {
        this.tabladetalles = tabladetalles;
    }

 
  
    
    public JTextField getTxt_direccion() {
        return txt_direccion;
    }
    public void setTxt_direccion(JTextField txt_direccion) {
        this.txt_direccion = txt_direccion;
    }
    public JTextField getTxt_nombres() {
        return txt_nombres;
    }
    public void setTxt_nombres(JTextField txt_nombres) {
        this.txt_nombres = txt_nombres;
    }
    public JTextField getTxt_telefono() {
        return txt_telefono;
    }
    public void setTxt_telefono(JTextField txt_telefono) {
        this.txt_telefono = txt_telefono;
    }
    public JTextField getTxt_total() {
        return txt_total;
    }
    public void setTxt_total(JTextField txt_total) {
        this.txt_total = txt_total;
    }

    
    /**
     * @param args the command line arguments
     */

    public JButton getBut_consultar() {
        return but_consultar;
    }

    public void setBut_consultar(JButton but_consultar) {
        this.but_consultar = but_consultar;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dlg_Factura;
    private LIB.FSTexFieldMD buscacabeza;
    private LIB.FSTexFieldMD buscadetalle;
    private javax.swing.JButton but_actualizar;
    private javax.swing.JButton but_atras;
    private javax.swing.JButton but_cancelar;
    private javax.swing.JButton but_consultar;
    private javax.swing.JButton but_limpiar;
    private javax.swing.JTable cabezafactura;
    private javax.swing.JButton facturasjasper;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private LIB.JEImagePanel jEImagePanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_apellidos;
    private javax.swing.JLabel lb_cedula;
    private javax.swing.JLabel lb_dia;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_facnumero;
    private javax.swing.JLabel lb_factura;
    private javax.swing.JLabel lb_fechanac;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_nacimiento;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_numfac;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTable table_fac;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//