// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class Vista_factura_formulario extends javax.swing.JFrame {

    /** Creates new form FACTURA_FORMULARIO */
    public Vista_factura_formulario() {
        initComponents();
        Vista_factura_formulario.this.setBackground(new Color(0,0,0,0));
        
        jtbuscacliente.addKeyListener(new VALIDACIONES.Numeros());
        
setIconImage(new ImageIcon(getClass().getResource("/ICONOS/iconocolibrie.jpg")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobotones = new javax.swing.ButtonGroup();
        botonesdepago = new javax.swing.ButtonGroup();
        ingresocliente = new javax.swing.JDialog();
        portadacaratula = new LIB.JEImagePanel();
        generarcodigocliente = new javax.swing.JButton();
        codigocliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        telefoo = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        crearcliente = new javax.swing.JButton();
        cancelarcrear = new javax.swing.JButton();
        jPanelRound1 = new LIB.JPanelRound();
        jEImagePanel1 = new LIB.JEImagePanel();
        lb_nombres = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        lb_apellido = new javax.swing.JLabel();
        but_aceptar = new javax.swing.JButton();
        lb_direccion = new javax.swing.JLabel();
        but_cancelar = new javax.swing.JButton();
        lb_telefono = new javax.swing.JLabel();
        dtcFechaNacimiento1 = new com.toedter.calendar.JDateChooser();
        lb_fecha = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        lb_id = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jPanelRound2 = new LIB.JPanelRound();
        jEImagePanel2 = new LIB.JEImagePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechafactura = new javax.swing.JLabel();
        codigofactura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        subtitulo1 = new javax.swing.JLabel();
        jtbuscacliente = new javax.swing.JTextField();
        buscarcliente = new javax.swing.JButton();
        ingresarcliente = new javax.swing.JButton();
        codigodelcliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacarrito = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cancelarventa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jasparin = new javax.swing.JButton();

        ingresocliente.setBackground(new java.awt.Color(255, 255, 255));
        ingresocliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        portadacaratula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Datos cliente.png"))); // NOI18N

        javax.swing.GroupLayout portadacaratulaLayout = new javax.swing.GroupLayout(portadacaratula);
        portadacaratula.setLayout(portadacaratulaLayout);
        portadacaratulaLayout.setHorizontalGroup(
            portadacaratulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        portadacaratulaLayout.setVerticalGroup(
            portadacaratulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        ingresocliente.getContentPane().add(portadacaratula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        generarcodigocliente.setText("GENERAR");
        ingresocliente.getContentPane().add(generarcodigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        codigocliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ingresocliente.getContentPane().add(codigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 180, 23));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("INGRESO   CLIENTE");
        ingresocliente.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 180, 30));

        jLabel5.setText("CEDULA");
        ingresocliente.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 20));

        jLabel6.setText("APELLIDO");
        ingresocliente.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 90, 20));

        jLabel7.setText("NOMBRE");
        ingresocliente.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 90, 20));

        jLabel8.setText("DIRECCION");
        ingresocliente.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 90, 20));

        jLabel9.setText("CORREO");
        ingresocliente.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 90, 20));

        jLabel10.setText("TELEFONO");
        ingresocliente.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 90, 20));
        ingresocliente.getContentPane().add(dtcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 200, -1));

        jLabel11.setText("NACIMIENTO");
        ingresocliente.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 80, 20));
        ingresocliente.getContentPane().add(telefoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 180, -1));
        ingresocliente.getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 180, -1));
        ingresocliente.getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 180, -1));
        ingresocliente.getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 180, -1));
        ingresocliente.getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 180, -1));
        ingresocliente.getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 180, -1));

        crearcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ACEPTAR ICO.png"))); // NOI18N
        crearcliente.setBorder(null);
        crearcliente.setBorderPainted(false);
        crearcliente.setContentAreaFilled(false);
        crearcliente.setFocusPainted(false);
        ingresocliente.getContentPane().add(crearcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        cancelarcrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        cancelarcrear.setBorder(null);
        cancelarcrear.setBorderPainted(false);
        cancelarcrear.setContentAreaFilled(false);
        cancelarcrear.setFocusPainted(false);
        ingresocliente.getContentPane().add(cancelarcrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, -1, -1));

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(null);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Datos cliente.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanelRound1.add(jEImagePanel1);
        jEImagePanel1.setBounds(0, 0, 420, 580);

        lb_nombres.setText("Nombres:");
        jPanelRound1.add(lb_nombres);
        lb_nombres.setBounds(520, 120, 46, 14);
        jPanelRound1.add(txt_correo);
        txt_correo.setBounds(620, 280, 193, 20);

        lb_apellido.setText("Apellidos:");
        jPanelRound1.add(lb_apellido);
        lb_apellido.setBounds(520, 160, 46, 14);

        but_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ACEPTAR ICO.png"))); // NOI18N
        but_aceptar.setBorder(null);
        but_aceptar.setBorderPainted(false);
        but_aceptar.setContentAreaFilled(false);
        but_aceptar.setFocusPainted(false);
        jPanelRound1.add(but_aceptar);
        but_aceptar.setBounds(460, 420, 180, 50);

        lb_direccion.setText("Dirección:");
        jPanelRound1.add(lb_direccion);
        lb_direccion.setBounds(520, 210, 47, 14);

        but_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_cancelar.setBorder(null);
        but_cancelar.setBorderPainted(false);
        but_cancelar.setContentAreaFilled(false);
        but_cancelar.setFocusPainted(false);
        jPanelRound1.add(but_cancelar);
        but_cancelar.setBounds(690, 410, 180, 60);

        lb_telefono.setText("Teléfono:");
        jPanelRound1.add(lb_telefono);
        lb_telefono.setBounds(520, 250, 46, 14);
        jPanelRound1.add(dtcFechaNacimiento1);
        dtcFechaNacimiento1.setBounds(620, 330, 200, 20);

        lb_fecha.setText("F. Nacimiento:");
        jPanelRound1.add(lb_fecha);
        lb_fecha.setBounds(520, 330, 69, 14);

        lb_correo.setText("Correo:");
        jPanelRound1.add(lb_correo);
        lb_correo.setBounds(520, 290, 37, 14);
        jPanelRound1.add(txt_id);
        txt_id.setBounds(620, 70, 190, 20);
        jPanelRound1.add(txt_nombres);
        txt_nombres.setBounds(620, 120, 190, 20);
        jPanelRound1.add(txt_apellidos);
        txt_apellidos.setBounds(620, 160, 190, 20);
        jPanelRound1.add(txt_direccion);
        txt_direccion.setBounds(620, 200, 190, 20);

        lb_id.setText("Id:");
        jPanelRound1.add(lb_id);
        lb_id.setBounds(520, 80, 14, 14);
        jPanelRound1.add(txt_telefono);
        txt_telefono.setBounds(620, 240, 190, 20);

        ingresocliente.getContentPane().add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound2.setOpaque(true);
        jPanelRound2.setLayout(null);

        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Facturas_1.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel2Layout = new javax.swing.GroupLayout(jEImagePanel2);
        jEImagePanel2.setLayout(jEImagePanel2Layout);
        jEImagePanel2Layout.setHorizontalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jEImagePanel2Layout.setVerticalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanelRound2.add(jEImagePanel2);
        jEImagePanel2.setBounds(0, 0, 390, 470);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(" FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 150, 20));

        fechafactura.setText("FECHA");
        jPanel1.add(fechafactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 180, -1));

        codigofactura.setText("CODIGO  FACTURA");
        jPanel1.add(codigofactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, -1));

        jPanelRound2.add(jPanel1);
        jPanel1.setBounds(390, 0, 620, 50);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo1.setText("EL COIGO DE LA FACTURA SE GENERARÁ  DE MANERA AUTOMATICA.");
        jPanel2.add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jtbuscacliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbuscaclienteKeyTyped(evt);
            }
        });
        jPanel2.add(jtbuscacliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, -1));

        buscarcliente.setText("BUSCAR");
        jPanel2.add(buscarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, -1));

        ingresarcliente.setText("INGRESAR");
        jPanel2.add(ingresarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, -1));

        codigodelcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(codigodelcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, 20));

        jLabel2.setText("CON  DATOS  CLIENTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 160, 20));

        jLabel3.setText("CODIGO  CONSUMIDOR  FINAL:: 0000000000");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 20));

        jPanelRound2.add(jPanel2);
        jPanel2.setBounds(390, 50, 620, 150);

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablacarrito.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablacarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "CANTIDAD", "PRECIO", "EXISTENCIA"
            }
        ));
        jScrollPane2.setViewportView(tablacarrito);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 90));

        jPanelRound2.add(jPanel3);
        jPanel3.setBounds(390, 200, 620, 200);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarventa.setBackground(new java.awt.Color(255, 0, 0));
        cancelarventa.setText("CANCELAR");
        jPanel4.add(cancelarventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setText("VENDER");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jasparin.setText("GENERAR   FACTURA");
        jPanel4.add(jasparin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanelRound2.add(jPanel4);
        jPanel4.setBounds(390, 400, 620, 70);

        getContentPane().add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbuscaclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbuscaclienteKeyTyped
        if(jtbuscacliente.getText().length()>=10){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SOLO HASTA 10 DIGITOS");
        }
    }//GEN-LAST:event_jtbuscaclienteKeyTyped

    public JButton getJasparin() {
        return jasparin;
    }

    public void setJasparin(JButton jasparin) {
        this.jasparin = jasparin;
    }
//codigocliente
    
    
    
    public JTextField getApellido() {
        return apellido;
    }

    public void setApellido(JTextField apellido) {
        this.apellido = apellido;
    }

    public JButton getCancelarcrear() {
        return cancelarcrear;
    }

    public void setCancelarcrear(JButton cancelarcrear) {
        this.cancelarcrear = cancelarcrear;
    }

    public JTextField getCedula() {
        return cedula;
    }

    public void setCedula(JTextField cedula) {
        this.cedula = cedula;
    }

    public JLabel getCodigodelcliente() {
        return codigodelcliente;
    }

    public void setCodigodelcliente(JLabel codigodelcliente) {
        this.codigodelcliente = codigodelcliente;
    }

    public JLabel getCodigocliente() {
        return codigocliente;
    }

    public void setCodigocliente(JLabel codigocliente) {
        this.codigocliente = codigocliente;
    }

    public JTextField getCorreo() {
        return correo;
    }

    public void setCorreo(JTextField correo) {
        this.correo = correo;
    }

    public JButton getCrearcliente() {
        return crearcliente;
    }

    public void setCrearcliente(JButton crearcliente) {
        this.crearcliente = crearcliente;
    }

    public JTextField getDireccion() {
        return direccion;
    }

    public void setDireccion(JTextField direccion) {
        this.direccion = direccion;
    }

    public JDateChooser getDtcFechaNacimiento() {
        return dtcFechaNacimiento;
    }

    public void setDtcFechaNacimiento(JDateChooser dtcFechaNacimiento) {
        this.dtcFechaNacimiento = dtcFechaNacimiento;
    }

    public JButton getGenerarcodigocliente() {
        return generarcodigocliente;
    }

    public void setGenerarcodigocliente(JButton generarcodigocliente) {
        this.generarcodigocliente = generarcodigocliente;
    }

    public JDialog getIngresocliente() {
        return ingresocliente;
    }

    public void setIngresocliente(JDialog ingresocliente) {
        this.ingresocliente = ingresocliente;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public JTextField getTelefoo() {
        return telefoo;
    }

    public void setTelefoo(JTextField telefoo) {
        this.telefoo = telefoo;
    }

    
    
    public JLabel getCodigofactura() {
        return codigofactura;
    }

    public void setCodigofactura(JLabel codigofactura) {
        this.codigofactura = codigofactura;
    }

    public JLabel getFechafactura() {
        return fechafactura;
    }

    public void setFechafactura(JLabel fechafactura) {
        this.fechafactura = fechafactura;
    }
 
//    public JRadioButton getBccondatos() {
//        return bccondatos;
//    }
//
//    public void setBccondatos(JRadioButton bccondatos) {
//        this.bccondatos = bccondatos;
//    }
//
//    public JRadioButton getBcfinal() {
//        return bcfinal;
//    }
//
//    public void setBcfinal(JRadioButton bcfinal) {
//        this.bcfinal = bcfinal;
//    }

    public ButtonGroup getBotonesdepago() {
        return botonesdepago;
    }

    public void setBotonesdepago(ButtonGroup botonesdepago) {
        this.botonesdepago = botonesdepago;
    }


    public JButton getBuscarcliente() {
        return buscarcliente;
    }

    public void setBuscarcliente(JButton buscarcliente) {
        this.buscarcliente = buscarcliente;
    }

    public JButton getCancelarventa() {
        return cancelarventa;
    }

    public void setCancelarventa(JButton cancelarventa) {
        this.cancelarventa = cancelarventa;
    }

    public ButtonGroup getGrupobotones() {
        return grupobotones;
    }

    public void setGrupobotones(ButtonGroup grupobotones) {
        this.grupobotones = grupobotones;
    }

    public JButton getIngresarcliente() {
        return ingresarcliente;
    }

    public void setIngresarcliente(JButton ingresarcliente) {
        this.ingresarcliente = ingresarcliente;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
 

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTextField getJtbuscacliente() {
        return jtbuscacliente;
    }

    public void setJtbuscacliente(JTextField jtbuscacliente) {
        this.jtbuscacliente = jtbuscacliente;
    }

    public JLabel getSubtitulo1() {
        return subtitulo1;
    }

    public void setSubtitulo1(JLabel subtitulo1) {
        this.subtitulo1 = subtitulo1;
    }

    public JTable getTablacarrito() {
        return tablacarrito;
    }

    public void setTablacarrito(JTable tablacarrito) {
        this.tablacarrito = tablacarrito;
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.ButtonGroup botonesdepago;
    private javax.swing.JButton buscarcliente;
    private javax.swing.JButton but_aceptar;
    private javax.swing.JButton but_cancelar;
    private javax.swing.JButton cancelarcrear;
    private javax.swing.JButton cancelarventa;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel codigocliente;
    private javax.swing.JLabel codigodelcliente;
    private javax.swing.JLabel codigofactura;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crearcliente;
    private javax.swing.JTextField direccion;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento1;
    private javax.swing.JLabel fechafactura;
    private javax.swing.JButton generarcodigocliente;
    private javax.swing.ButtonGroup grupobotones;
    private javax.swing.JButton ingresarcliente;
    private javax.swing.JDialog ingresocliente;
    private javax.swing.JButton jButton2;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jasparin;
    private javax.swing.JTextField jtbuscacliente;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JTextField nombre;
    private LIB.JEImagePanel portadacaratula;
    private javax.swing.JLabel subtitulo1;
    public javax.swing.JTable tablacarrito;
    private javax.swing.JTextField telefoo;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//