// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//
package VISTA;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class Vista_factura_formulario extends javax.swing.JFrame {

    /** Creates new form FACTURA_FORMULARIO */
    public Vista_factura_formulario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobotones = new javax.swing.ButtonGroup();
        botonesdepago = new javax.swing.ButtonGroup();
        ingresocliente = new javax.swing.JDialog();
        generarcodigocliente = new javax.swing.JButton();
        codigocliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        telefoo = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        crearcliente = new javax.swing.JButton();
        cancelarcrear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechafactura = new javax.swing.JLabel();
        codigofactura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        subtitulo1 = new javax.swing.JLabel();
        bcfinal = new javax.swing.JRadioButton();
        bccondatos = new javax.swing.JRadioButton();
        jtbuscacliente = new javax.swing.JTextField();
        buscarcliente = new javax.swing.JButton();
        ingresarcliente = new javax.swing.JButton();
        codigodelcliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacarrito = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cancelarventa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jasparin = new javax.swing.JButton();

        ingresocliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generarcodigocliente.setText("GENERAR");
        ingresocliente.getContentPane().add(generarcodigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        codigocliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ingresocliente.getContentPane().add(codigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 180, 23));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("INGRESO   CLIENTE");
        ingresocliente.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, 30));

        jLabel5.setText("CEDULA");
        ingresocliente.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, 20));

        jLabel6.setText("APELLIDO");
        ingresocliente.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, 20));

        jLabel7.setText("NOMBRE");
        ingresocliente.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 20));

        jLabel8.setText("DIRECCION");
        ingresocliente.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 20));

        jLabel9.setText("CORREO");
        ingresocliente.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, 20));

        jLabel10.setText("TELEFONO");
        ingresocliente.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 20));
        ingresocliente.getContentPane().add(dtcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 200, -1));

        jLabel11.setText("NACIMIENTO");
        ingresocliente.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 80, 20));
        ingresocliente.getContentPane().add(telefoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 180, -1));
        ingresocliente.getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, -1));
        ingresocliente.getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, -1));
        ingresocliente.getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 180, -1));
        ingresocliente.getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, -1));
        ingresocliente.getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, -1));

        crearcliente.setText("INGRESAR   ");
        ingresocliente.getContentPane().add(crearcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        cancelarcrear.setText("CANCELAR");
        ingresocliente.getContentPane().add(cancelarcrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(" FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 150, 20));

        fechafactura.setText("FECHA");
        jPanel1.add(fechafactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, -1));

        codigofactura.setText("CODIGO  FACTURA");
        jPanel1.add(codigofactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo1.setText("EL COIGO DE LA FACTURA SE GENERARÁ  DE MANERA AUTOMATICA.");
        jPanel2.add(subtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        grupobotones.add(bcfinal);
        bcfinal.setText("CONSUMIDOR FINAL");
        jPanel2.add(bcfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        grupobotones.add(bccondatos);
        bccondatos.setText("DATOS");
        jPanel2.add(bccondatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));
        jPanel2.add(jtbuscacliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, -1));

        buscarcliente.setText("BUSCAR");
        jPanel2.add(buscarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, -1));

        ingresarcliente.setText("INGRESAR");
        jPanel2.add(ingresarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, -1));

        codigodelcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(codigodelcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 150));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablacarrito.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablacarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "CANTIDAD", "PRECIO", "EXISTENCIA"
            }
        ));
        jScrollPane2.setViewportView(tablacarrito);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 620, 200));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarventa.setBackground(new java.awt.Color(255, 0, 0));
        cancelarventa.setText("CANCELAR");
        jPanel4.add(cancelarventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setText("VENDER");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jasparin.setText("GENERAR   FACTURA");
        jPanel4.add(jasparin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 620, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getJasparin() {
        return jasparin;
    }

    public void setJasparin(JButton jasparin) {
        this.jasparin = jasparin;
    }
//codigocliente
    
    
    
    public JTextField getApellido() {
        return apellido;
    }

    public void setApellido(JTextField apellido) {
        this.apellido = apellido;
    }

    public JButton getCancelarcrear() {
        return cancelarcrear;
    }

    public void setCancelarcrear(JButton cancelarcrear) {
        this.cancelarcrear = cancelarcrear;
    }

    public JTextField getCedula() {
        return cedula;
    }

    public void setCedula(JTextField cedula) {
        this.cedula = cedula;
    }

    public JLabel getCodigodelcliente() {
        return codigodelcliente;
    }

    public void setCodigodelcliente(JLabel codigodelcliente) {
        this.codigodelcliente = codigodelcliente;
    }

    public JLabel getCodigocliente() {
        return codigocliente;
    }

    public void setCodigocliente(JLabel codigocliente) {
        this.codigocliente = codigocliente;
    }

    public JTextField getCorreo() {
        return correo;
    }

    public void setCorreo(JTextField correo) {
        this.correo = correo;
    }

    public JButton getCrearcliente() {
        return crearcliente;
    }

    public void setCrearcliente(JButton crearcliente) {
        this.crearcliente = crearcliente;
    }

    public JTextField getDireccion() {
        return direccion;
    }

    public void setDireccion(JTextField direccion) {
        this.direccion = direccion;
    }

    public JDateChooser getDtcFechaNacimiento() {
        return dtcFechaNacimiento;
    }

    public void setDtcFechaNacimiento(JDateChooser dtcFechaNacimiento) {
        this.dtcFechaNacimiento = dtcFechaNacimiento;
    }

    public JButton getGenerarcodigocliente() {
        return generarcodigocliente;
    }

    public void setGenerarcodigocliente(JButton generarcodigocliente) {
        this.generarcodigocliente = generarcodigocliente;
    }

    public JDialog getIngresocliente() {
        return ingresocliente;
    }

    public void setIngresocliente(JDialog ingresocliente) {
        this.ingresocliente = ingresocliente;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JTextField getNombre() {
        return nombre;
    }

    public void setNombre(JTextField nombre) {
        this.nombre = nombre;
    }

    public JTextField getTelefoo() {
        return telefoo;
    }

    public void setTelefoo(JTextField telefoo) {
        this.telefoo = telefoo;
    }

    
    
    public JLabel getCodigofactura() {
        return codigofactura;
    }

    public void setCodigofactura(JLabel codigofactura) {
        this.codigofactura = codigofactura;
    }

    public JLabel getFechafactura() {
        return fechafactura;
    }

    public void setFechafactura(JLabel fechafactura) {
        this.fechafactura = fechafactura;
    }
 
    public JRadioButton getBccondatos() {
        return bccondatos;
    }

    public void setBccondatos(JRadioButton bccondatos) {
        this.bccondatos = bccondatos;
    }

    public JRadioButton getBcfinal() {
        return bcfinal;
    }

    public void setBcfinal(JRadioButton bcfinal) {
        this.bcfinal = bcfinal;
    }

    public ButtonGroup getBotonesdepago() {
        return botonesdepago;
    }

    public void setBotonesdepago(ButtonGroup botonesdepago) {
        this.botonesdepago = botonesdepago;
    }


    public JButton getBuscarcliente() {
        return buscarcliente;
    }

    public void setBuscarcliente(JButton buscarcliente) {
        this.buscarcliente = buscarcliente;
    }

    public JButton getCancelarventa() {
        return cancelarventa;
    }

    public void setCancelarventa(JButton cancelarventa) {
        this.cancelarventa = cancelarventa;
    }

    public ButtonGroup getGrupobotones() {
        return grupobotones;
    }

    public void setGrupobotones(ButtonGroup grupobotones) {
        this.grupobotones = grupobotones;
    }

    public JButton getIngresarcliente() {
        return ingresarcliente;
    }

    public void setIngresarcliente(JButton ingresarcliente) {
        this.ingresarcliente = ingresarcliente;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
 

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTextField getJtbuscacliente() {
        return jtbuscacliente;
    }

    public void setJtbuscacliente(JTextField jtbuscacliente) {
        this.jtbuscacliente = jtbuscacliente;
    }

    public JLabel getSubtitulo1() {
        return subtitulo1;
    }

    public void setSubtitulo1(JLabel subtitulo1) {
        this.subtitulo1 = subtitulo1;
    }

    public JTable getTablacarrito() {
        return tablacarrito;
    }

    public void setTablacarrito(JTable tablacarrito) {
        this.tablacarrito = tablacarrito;
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JRadioButton bccondatos;
    private javax.swing.JRadioButton bcfinal;
    private javax.swing.ButtonGroup botonesdepago;
    private javax.swing.JButton buscarcliente;
    private javax.swing.JButton cancelarcrear;
    private javax.swing.JButton cancelarventa;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel codigocliente;
    private javax.swing.JLabel codigodelcliente;
    private javax.swing.JLabel codigofactura;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crearcliente;
    private javax.swing.JTextField direccion;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private javax.swing.JLabel fechafactura;
    private javax.swing.JButton generarcodigocliente;
    private javax.swing.ButtonGroup grupobotones;
    private javax.swing.JButton ingresarcliente;
    private javax.swing.JDialog ingresocliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jasparin;
    private javax.swing.JTextField jtbuscacliente;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel subtitulo1;
    public javax.swing.JTable tablacarrito;
    private javax.swing.JTextField telefoo;
    // End of variables declaration//GEN-END:variables
}
// ESPINOZA ALFONSO DAVID, FABIAN GUTAMA, JUAN MATUTE, ESTEFANIA MUÑOZ//