/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_ingreso_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Ingresocliente
     */
    public Vista_ingreso_cliente() {
        initComponents();
        Vista_ingreso_cliente.this.setBackground(new Color(0, 0, 0, 0));

    }

    public JButton getBut_aceptar() {
        return but_aceptar;
    }

    public void setBut_aceptar(JButton but_aceptar) {
        this.but_aceptar = but_aceptar;
    }

    public JButton getBut_cancelar() {
        return but_cancelar;
    }

    public void setBut_cancelar(JButton but_cancelar) {
        this.but_cancelar = but_cancelar;
    }

    public JDateChooser getDtcFechaNacimiento() {
        return dtcFechaNacimiento;
    }

    public void setDtcFechaNacimiento(JDateChooser dtcFechaNacimiento) {
        this.dtcFechaNacimiento = dtcFechaNacimiento;
    }

    public JLabel getLb_apellido() {
        return lb_apellido;
    }

    public void setLb_apellido(JLabel lb_apellido) {
        this.lb_apellido = lb_apellido;
    }

  

    public JLabel getLb_correo() {
        return lb_correo;
    }

    public void setLb_correo(JLabel lb_correo) {
        this.lb_correo = lb_correo;
    }

    public JLabel getLb_direccion() {
        return lb_direccion;
    }

    public void setLb_direccion(JLabel lb_direccion) {
        this.lb_direccion = lb_direccion;
    }

    public JLabel getLb_fecha() {
        return lb_fecha;
    }

    public void setLb_fecha(JLabel lb_fecha) {
        this.lb_fecha = lb_fecha;
    }

    public JLabel getLb_id() {
        return lb_id;
    }

    public void setLb_id(JLabel lb_id) {
        this.lb_id = lb_id;
    }

    public JLabel getLb_nombres() {
        return lb_nombres;
    }

    public void setLb_nombres(JLabel lb_nombres) {
        this.lb_nombres = lb_nombres;
    }

    public JLabel getLb_telefono() {
        return lb_telefono;
    }

    public void setLb_telefono(JLabel lb_telefono) {
        this.lb_telefono = lb_telefono;
    }

    public JTextField getTxt_apellidos() {
        return txt_apellidos;
    }

    public void setTxt_apellidos(JTextField txt_apellidos) {
        this.txt_apellidos = txt_apellidos;
    }

    public JTextField getTxt_correo() {
        return txt_correo;
    }

    public void setTxt_correo(JTextField txt_correo) {
        this.txt_correo = txt_correo;
    }

    public JTextField getTxt_direccion() {
        return txt_direccion;
    }

    public void setTxt_direccion(JTextField txt_direccion) {
        this.txt_direccion = txt_direccion;
    }

    public JTextField getTxt_id() {
        return txt_id;
    }

    public void setTxt_id(JTextField txt_id) {
        this.txt_id = txt_id;
    }

    public JTextField getTxt_nombres() {
        return txt_nombres;
    }

    public void setTxt_nombres(JTextField txt_nombres) {
        this.txt_nombres = txt_nombres;
    }

    public JTextField getTxt_telefono() {
        return txt_telefono;
    }

    public void setTxt_telefono(JTextField txt_telefono) {
        this.txt_telefono = txt_telefono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRound1 = new LIB.JPanelRound();
        jEImagePanel1 = new LIB.JEImagePanel();
        lb_nombres = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        lb_apellido = new javax.swing.JLabel();
        but_aceptar = new javax.swing.JButton();
        lb_direccion = new javax.swing.JLabel();
        but_cancelar = new javax.swing.JButton();
        lb_telefono = new javax.swing.JLabel();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        lb_fecha = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        lb_id = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(911, 580));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(null);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Datos cliente.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanelRound1.add(jEImagePanel1);
        jEImagePanel1.setBounds(0, 0, 420, 580);

        lb_nombres.setText("Nombres:");
        jPanelRound1.add(lb_nombres);
        lb_nombres.setBounds(520, 120, 46, 14);
        jPanelRound1.add(txt_correo);
        txt_correo.setBounds(620, 280, 193, 20);

        lb_apellido.setText("Apellidos:");
        jPanelRound1.add(lb_apellido);
        lb_apellido.setBounds(520, 160, 46, 14);

        but_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ACEPTAR ICO.png"))); // NOI18N
        but_aceptar.setBorder(null);
        but_aceptar.setBorderPainted(false);
        but_aceptar.setContentAreaFilled(false);
        but_aceptar.setFocusPainted(false);
        jPanelRound1.add(but_aceptar);
        but_aceptar.setBounds(580, 390, 180, 50);

        lb_direccion.setText("Dirección:");
        jPanelRound1.add(lb_direccion);
        lb_direccion.setBounds(520, 210, 47, 14);

        but_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/REGRESAR ICO.png"))); // NOI18N
        but_cancelar.setBorder(null);
        but_cancelar.setBorderPainted(false);
        but_cancelar.setContentAreaFilled(false);
        but_cancelar.setFocusPainted(false);
        jPanelRound1.add(but_cancelar);
        but_cancelar.setBounds(710, 470, 180, 60);

        lb_telefono.setText("Teléfono:");
        jPanelRound1.add(lb_telefono);
        lb_telefono.setBounds(520, 250, 46, 14);
        jPanelRound1.add(dtcFechaNacimiento);
        dtcFechaNacimiento.setBounds(620, 330, 200, 20);

        lb_fecha.setText("F. Nacimiento:");
        jPanelRound1.add(lb_fecha);
        lb_fecha.setBounds(520, 330, 69, 14);

        lb_correo.setText("Correo:");
        jPanelRound1.add(lb_correo);
        lb_correo.setBounds(520, 290, 37, 14);
        jPanelRound1.add(txt_id);
        txt_id.setBounds(620, 70, 190, 20);
        jPanelRound1.add(txt_nombres);
        txt_nombres.setBounds(620, 120, 190, 20);
        jPanelRound1.add(txt_apellidos);
        txt_apellidos.setBounds(620, 160, 190, 20);
        jPanelRound1.add(txt_direccion);
        txt_direccion.setBounds(620, 200, 190, 20);

        lb_id.setText("Id:");
        jPanelRound1.add(lb_id);
        lb_id.setBounds(520, 80, 14, 14);
        jPanelRound1.add(txt_telefono);
        txt_telefono.setBounds(620, 240, 190, 20);

        getContentPane().add(jPanelRound1);
        jPanelRound1.setBounds(0, 0, 910, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_aceptar;
    private javax.swing.JButton but_cancelar;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nombres;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
